/*
 * generated by Xtext
 */
package org.eclipse.papyrus.uml.textedit.parameter.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

import org.antlr.runtime.RecognitionException;
import org.eclipse.papyrus.uml.textedit.parameter.xtext.services.UmlParameterGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

public class UmlParameterParser extends AbstractContentAssistParser {

	@Inject
	private UmlParameterGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected org.eclipse.papyrus.uml.textedit.parameter.xtext.ui.contentassist.antlr.internal.InternalUmlParameterParser createParser() {
		org.eclipse.papyrus.uml.textedit.parameter.xtext.ui.contentassist.antlr.internal.InternalUmlParameterParser result = new org.eclipse.papyrus.uml.textedit.parameter.xtext.ui.contentassist.antlr.internal.InternalUmlParameterParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getParameterRuleAccess().getAlternatives_3_1(), "rule__ParameterRule__Alternatives_3_1");
					put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
					put(grammarAccess.getRealValueAccess().getAlternatives(), "rule__RealValue__Alternatives");
					put(grammarAccess.getUnlimitedLiteralAccess().getAlternatives(), "rule__UnlimitedLiteral__Alternatives");
					put(grammarAccess.getModifierKindAccess().getAlternatives(), "rule__ModifierKind__Alternatives");
					put(grammarAccess.getEffectKindAccess().getAlternatives(), "rule__EffectKind__Alternatives");
					put(grammarAccess.getBooleanLiteralsAccess().getAlternatives(), "rule__BooleanLiterals__Alternatives");
					put(grammarAccess.getVisibilityKindAccess().getAlternatives(), "rule__VisibilityKind__Alternatives");
					put(grammarAccess.getDirectionAccess().getAlternatives(), "rule__Direction__Alternatives");
					put(grammarAccess.getParameterRuleAccess().getGroup(), "rule__ParameterRule__Group__0");
					put(grammarAccess.getParameterRuleAccess().getGroup_3(), "rule__ParameterRule__Group_3__0");
					put(grammarAccess.getModifiersRuleAccess().getGroup(), "rule__ModifiersRule__Group__0");
					put(grammarAccess.getModifiersRuleAccess().getGroup_2(), "rule__ModifiersRule__Group_2__0");
					put(grammarAccess.getModifiersRuleAccess().getGroup_2_1(), "rule__ModifiersRule__Group_2_1__0");
					put(grammarAccess.getEffectRuleAccess().getGroup(), "rule__EffectRule__Group__0");
					put(grammarAccess.getDefaultValueRuleAccess().getGroup(), "rule__DefaultValueRule__Group__0");
					put(grammarAccess.getRealValueAccess().getGroup_0(), "rule__RealValue__Group_0__0");
					put(grammarAccess.getRealValueAccess().getGroup_1(), "rule__RealValue__Group_1__0");
					put(grammarAccess.getRealValueAccess().getGroup_2(), "rule__RealValue__Group_2__0");
					put(grammarAccess.getNullValueAccess().getGroup(), "rule__NullValue__Group__0");
					put(grammarAccess.getNoValueAccess().getGroup(), "rule__NoValue__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getTypeRuleAccess().getGroup(), "rule__TypeRule__Group__0");
					put(grammarAccess.getMultiplicityRuleAccess().getGroup(), "rule__MultiplicityRule__Group__0");
					put(grammarAccess.getMultiplicityRuleAccess().getGroup_2(), "rule__MultiplicityRule__Group_2__0");
					put(grammarAccess.getParameterRuleAccess().getVisibilityAssignment_0(), "rule__ParameterRule__VisibilityAssignment_0");
					put(grammarAccess.getParameterRuleAccess().getDirectionAssignment_1(), "rule__ParameterRule__DirectionAssignment_1");
					put(grammarAccess.getParameterRuleAccess().getNameAssignment_2(), "rule__ParameterRule__NameAssignment_2");
					put(grammarAccess.getParameterRuleAccess().getTypeAssignment_3_1_0(), "rule__ParameterRule__TypeAssignment_3_1_0");
					put(grammarAccess.getParameterRuleAccess().getTypeUndefinedAssignment_3_1_1(), "rule__ParameterRule__TypeUndefinedAssignment_3_1_1");
					put(grammarAccess.getParameterRuleAccess().getMultiplicityAssignment_4(), "rule__ParameterRule__MultiplicityAssignment_4");
					put(grammarAccess.getParameterRuleAccess().getModifiersAssignment_5(), "rule__ParameterRule__ModifiersAssignment_5");
					put(grammarAccess.getParameterRuleAccess().getEffectAssignment_6(), "rule__ParameterRule__EffectAssignment_6");
					put(grammarAccess.getParameterRuleAccess().getDefaultValueAssignment_7(), "rule__ParameterRule__DefaultValueAssignment_7");
					put(grammarAccess.getModifiersRuleAccess().getValuesAssignment_2_0(), "rule__ModifiersRule__ValuesAssignment_2_0");
					put(grammarAccess.getModifiersRuleAccess().getValuesAssignment_2_1_1(), "rule__ModifiersRule__ValuesAssignment_2_1_1");
					put(grammarAccess.getModifierSpecificationAccess().getValueAssignment(), "rule__ModifierSpecification__ValueAssignment");
					put(grammarAccess.getVisibilityRuleAccess().getVisibilityAssignment(), "rule__VisibilityRule__VisibilityAssignment");
					put(grammarAccess.getDirectionRuleAccess().getDirectionAssignment(), "rule__DirectionRule__DirectionAssignment");
					put(grammarAccess.getEffectRuleAccess().getEffectKindAssignment_2(), "rule__EffectRule__EffectKindAssignment_2");
					put(grammarAccess.getDefaultValueRuleAccess().getDefaultAssignment_1(), "rule__DefaultValueRule__DefaultAssignment_1");
					put(grammarAccess.getIntValueAccess().getLiteralIntegerAssignment(), "rule__IntValue__LiteralIntegerAssignment");
					put(grammarAccess.getStringValueAccess().getLiteralStringAssignment(), "rule__StringValue__LiteralStringAssignment");
					put(grammarAccess.getBooleanValueAccess().getLiteralBooleanAssignment(), "rule__BooleanValue__LiteralBooleanAssignment");
					put(grammarAccess.getRealValueAccess().getIntegerAssignment_0_0(), "rule__RealValue__IntegerAssignment_0_0");
					put(grammarAccess.getRealValueAccess().getFractionAssignment_1_1(), "rule__RealValue__FractionAssignment_1_1");
					put(grammarAccess.getRealValueAccess().getIntegerAssignment_2_0(), "rule__RealValue__IntegerAssignment_2_0");
					put(grammarAccess.getRealValueAccess().getFractionAssignment_2_2(), "rule__RealValue__FractionAssignment_2_2");
					put(grammarAccess.getQualifiedNameAccess().getPathAssignment_0(), "rule__QualifiedName__PathAssignment_0");
					put(grammarAccess.getQualifiedNameAccess().getRemainingAssignment_2(), "rule__QualifiedName__RemainingAssignment_2");
					put(grammarAccess.getTypeRuleAccess().getPathAssignment_0(), "rule__TypeRule__PathAssignment_0");
					put(grammarAccess.getTypeRuleAccess().getTypeAssignment_1(), "rule__TypeRule__TypeAssignment_1");
					put(grammarAccess.getMultiplicityRuleAccess().getBoundsAssignment_1(), "rule__MultiplicityRule__BoundsAssignment_1");
					put(grammarAccess.getMultiplicityRuleAccess().getBoundsAssignment_2_1(), "rule__MultiplicityRule__BoundsAssignment_2_1");
					put(grammarAccess.getBoundSpecificationAccess().getValueAssignment(), "rule__BoundSpecification__ValueAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.eclipse.papyrus.uml.textedit.parameter.xtext.ui.contentassist.antlr.internal.InternalUmlParameterParser typedParser = (org.eclipse.papyrus.uml.textedit.parameter.xtext.ui.contentassist.antlr.internal.InternalUmlParameterParser) parser;
			typedParser.entryRuleParameterRule();
			return typedParser.getFollowElements();
		} catch (RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public UmlParameterGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UmlParameterGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
