/// @defgroup SNA_Examples_IDLExtra_defn IDLExtra_defn
/// @{
/// 
/// @file SNA_Examples_IDLExtra_defn.idl
/// @brief IDLExtra_defn definitions definition IDL file

//=========================================================

#ifndef CX_SNA_EXAMPLES_IDLEXTRA_DEFN_IDL
#define CX_SNA_EXAMPLES_IDLEXTRA_DEFN_IDL


/// @namespace SNA_Examples 
module SNA_Examples {

    /// this is constant
    const long MAX = 4;
};

#endif // CX_SNA_EXAMPLES_IDLEXTRA_DEFN_IDL

/// @}

