/// @defgroup AGSP_GPS_msg GPS_msg
/// @{
/// 
/// @file AGSP_GPS_msg.idl
/// @brief GPS_msg message definition IDL file

//=========================================================

#ifndef CX_SURVEILLANCEPROCESSOR_ASM__GIMBAL_GPS_ADAPTER_COMP__PORTS__AGSP_GPS_MSG_IDL
#define CX_SURVEILLANCEPROCESSOR_ASM__GIMBAL_GPS_ADAPTER_COMP__PORTS__AGSP_GPS_MSG_IDL

#include "AGSP_Common_defn.idl"
#pragma ndds typesupport "AGSP_GPS_msgSupport.h"

/// @namespace AGSP 
module AGSP {

    /// @struct GPS_msg
    struct GPS_msg {
        AGSP::SystemTime gpsTime;
        double gpsLat;

        /// // Installed height above floor (fixed)
        double gpsLon;

        /// // Offset angle of camera center azimuth from north (fixed)
        double floorHeight;

        /// // Camera pointing azimuth angle from calibrated center (+/-
        /// degrees)
        double azCenterOffset;

        /// // Camera elevation pointing angle from level (+/- degrees)
        double azAngle;
        double elAngle;
    }; //@top-level true
};

#endif // CX_SURVEILLANCEPROCESSOR_ASM__GIMBAL_GPS_ADAPTER_COMP__PORTS__AGSP_GPS_MSG_IDL

/// @}

