/// @defgroup AGSP_GG_Status_msg GG_Status_msg
/// @{
/// 
/// @file AGSP_GG_Status_msg.idl
/// @brief GG_Status_msg message definition IDL file

//=========================================================

#ifndef CX_SURVEILLANCEPROCESSOR_ASM__GIMBAL_GPS_ADAPTER_COMP__PORTS__AGSP_GG_STATUS_MSG_IDL
#define CX_SURVEILLANCEPROCESSOR_ASM__GIMBAL_GPS_ADAPTER_COMP__PORTS__AGSP_GG_STATUS_MSG_IDL

#include "AGSP_HSManager_defn.idl"
#pragma ndds typesupport "AGSP_GG_Status_msgSupport.h"

/// @namespace AGSP 
module AGSP {

    /// @struct GG_Status_msg
    struct GG_Status_msg {
        AGSP::SensorStatus gimbalGpsStatus;
    }; //@top-level true
};

#endif // CX_SURVEILLANCEPROCESSOR_ASM__GIMBAL_GPS_ADAPTER_COMP__PORTS__AGSP_GG_STATUS_MSG_IDL

/// @}

