<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="queries" nsURI="http://www.eclipse.org/ocl/2022/Queries" nsPrefix="queries">
  <eClassifiers xsi:type="ecore:EClass" name="QueryModel" eSuperTypes="Pivot.ecore#T-pivot-Model">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A QueryModel aggregates multiple QueryResults as a saveable model"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="results" upperBound="-1"
        eType="#//QueryResult" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryResult" eSuperTypes="Pivot.ecore#T-pivot-Element">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A QueryResult pairs a query with its self context and evaluation result"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="self" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="result" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="ecore:EClass Pivot.ecore#T-pivot-ExpressionInOCL" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass Pivot.ecore#T-pivot-OCLExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="errors" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
