package CF.DevicePackage;


/**
* CF/DevicePackage/AdminType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/


/* This enumeration type defines a Device's administrative states.
             The administrative state indicates the permission to use or
             prohibition against using the Device.  */
public class AdminType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static CF.DevicePackage.AdminType[] __array = new CF.DevicePackage.AdminType [__size];

  public static final int _LOCKED = 0;
  public static final CF.DevicePackage.AdminType LOCKED = new CF.DevicePackage.AdminType(_LOCKED);
  public static final int _SHUTTING_DOWN = 1;
  public static final CF.DevicePackage.AdminType SHUTTING_DOWN = new CF.DevicePackage.AdminType(_SHUTTING_DOWN);
  public static final int _UNLOCKED = 2;
  public static final CF.DevicePackage.AdminType UNLOCKED = new CF.DevicePackage.AdminType(_UNLOCKED);

  public int value ()
  {
    return __value;
  }

  public static CF.DevicePackage.AdminType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected AdminType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class AdminType
