package CF.DevicePackage;


/**
* CF/DevicePackage/InvalidCapacity.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/

public final class InvalidCapacity extends org.omg.CORBA.UserException
{

  /* The message indicates the reason for the invalid capacity. */
  public String msg = null;

  /* The invalid capacities sent to the allocateCapacity operation.*/
  public CF.DataType capacities[] = null;

  public InvalidCapacity ()
  {
    super(InvalidCapacityHelper.id());
  } // ctor

  public InvalidCapacity (String _msg, CF.DataType[] _capacities)
  {
    super(InvalidCapacityHelper.id());
    msg = _msg;
    capacities = _capacities;
  } // ctor


  public InvalidCapacity (String $reason, String _msg, CF.DataType[] _capacities)
  {
    super(InvalidCapacityHelper.id() + "  " + $reason);
    msg = _msg;
    capacities = _capacities;
  } // ctor

} // class InvalidCapacity
