package CF.DomainManagerPackage;

/**
* CF/DomainManagerPackage/AlreadyConnectedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/

public final class AlreadyConnectedHolder implements org.omg.CORBA.portable.Streamable
{
  public CF.DomainManagerPackage.AlreadyConnected value = null;

  public AlreadyConnectedHolder ()
  {
  }

  public AlreadyConnectedHolder (CF.DomainManagerPackage.AlreadyConnected initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CF.DomainManagerPackage.AlreadyConnectedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CF.DomainManagerPackage.AlreadyConnectedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CF.DomainManagerPackage.AlreadyConnectedHelper.type ();
  }

}
