package CF.DomainManagerPackage;


/**
* CF/DomainManagerPackage/ApplicationFactorySequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/


/* This type defines an unbounded sequence of ApplicationFactories. */
public final class ApplicationFactorySequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public CF.ApplicationFactory value[] = null;

  public ApplicationFactorySequenceHolder ()
  {
  }

  public ApplicationFactorySequenceHolder (CF.ApplicationFactory[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CF.DomainManagerPackage.ApplicationFactorySequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CF.DomainManagerPackage.ApplicationFactorySequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CF.DomainManagerPackage.ApplicationFactorySequenceHelper.type ();
  }

}
