package CF.DomainManagerPackage;

/**
* CF/DomainManagerPackage/ApplicationAlreadyInstalledHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/

public final class ApplicationAlreadyInstalledHolder implements org.omg.CORBA.portable.Streamable
{
  public CF.DomainManagerPackage.ApplicationAlreadyInstalled value = null;

  public ApplicationAlreadyInstalledHolder ()
  {
  }

  public ApplicationAlreadyInstalledHolder (CF.DomainManagerPackage.ApplicationAlreadyInstalled initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CF.DomainManagerPackage.ApplicationAlreadyInstalledHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CF.DomainManagerPackage.ApplicationAlreadyInstalledHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CF.DomainManagerPackage.ApplicationAlreadyInstalledHelper.type ();
  }

}
