package CF.DomainManagerPackage;


/**
* CF/DomainManagerPackage/ApplicationSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/


/* This type defines an unbounded sequence of Applications. */
public final class ApplicationSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public CF.Application value[] = null;

  public ApplicationSequenceHolder ()
  {
  }

  public ApplicationSequenceHolder (CF.Application[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CF.DomainManagerPackage.ApplicationSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CF.DomainManagerPackage.ApplicationSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CF.DomainManagerPackage.ApplicationSequenceHelper.type ();
  }

}
