package CF.DomainManagerPackage;


/**
* CF/DomainManagerPackage/ApplicationUninstallationError.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/

public final class ApplicationUninstallationError extends org.omg.CORBA.UserException
{
  public CF.ErrorNumberType errorNumber = null;
  public String msg = null;

  public ApplicationUninstallationError ()
  {
    super(ApplicationUninstallationErrorHelper.id());
  } // ctor

  public ApplicationUninstallationError (CF.ErrorNumberType _errorNumber, String _msg)
  {
    super(ApplicationUninstallationErrorHelper.id());
    errorNumber = _errorNumber;
    msg = _msg;
  } // ctor


  public ApplicationUninstallationError (String $reason, CF.ErrorNumberType _errorNumber, String _msg)
  {
    super(ApplicationUninstallationErrorHelper.id() + "  " + $reason);
    errorNumber = _errorNumber;
    msg = _msg;
  } // ctor

} // class ApplicationUninstallationError
