package CF.DomainManagerPackage;


/**
* CF/DomainManagerPackage/DeviceManagerNotRegistered.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/

public final class DeviceManagerNotRegistered extends org.omg.CORBA.UserException
{

  public DeviceManagerNotRegistered ()
  {
    super(DeviceManagerNotRegisteredHelper.id());
  } // ctor


  public DeviceManagerNotRegistered (String $reason)
  {
    super(DeviceManagerNotRegisteredHelper.id() + "  " + $reason);
  } // ctor

} // class DeviceManagerNotRegistered
