package CF.DomainManagerPackage;


/**
* CF/DomainManagerPackage/InvalidIdentifier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/

public final class InvalidIdentifier extends org.omg.CORBA.UserException
{

  public InvalidIdentifier ()
  {
    super(InvalidIdentifierHelper.id());
  } // ctor


  public InvalidIdentifier (String $reason)
  {
    super(InvalidIdentifierHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidIdentifier
