package CF.PortSupplierPackage;

/**
* CF/PortSupplierPackage/UnknownPortHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/

public final class UnknownPortHolder implements org.omg.CORBA.portable.Streamable
{
  public CF.PortSupplierPackage.UnknownPort value = null;

  public UnknownPortHolder ()
  {
  }

  public UnknownPortHolder (CF.PortSupplierPackage.UnknownPort initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CF.PortSupplierPackage.UnknownPortHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CF.PortSupplierPackage.UnknownPortHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CF.PortSupplierPackage.UnknownPortHelper.type ();
  }

}
