//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
// Copyright (c) Northrop Grumman Corporation 2020 -- ALL RIGHTS RESERVED
//==============================================================================
//
//==============================================================================
// EXPORT REGULATIONS (EAR99)
//==============================================================================
// DISCLOSURE: 
//
// Warning - This data is subject to the Export Administration Act (Title 22 
// U.S.C. App. 2401 et seq.), as amended. The implementing regulation for 
// this statute is the Export Administration Regulations (EAR) (15 C.F.R.
// 730-774). It may not be transferred, either in its original form, derivative 
// documents, or after being incorporated into other data without first 
// obtaining approval from the U.S. government or as otherwise authorized by 
// U.S. law and regulations. 
//==============================================================================
/// @defgroup SNA_Examples_PSDD_defn defn
/// @{
/// 
/// @file SNA_Examples_PSDD_defn.idl
/// @brief defn definitions definition IDL file

//=========================================================

#ifndef CX_PORTS__PSDDPUBSUB__SNA_EXAMPLES_PSDD_DEFN_IDL
#define CX_PORTS__PSDDPUBSUB__SNA_EXAMPLES_PSDD_DEFN_IDL


/// @brief SNA_Examples_PSDD 
module SNA_Examples_PSDD {

    /// @enum PSDD_State
    ///
    /// Example enumeration of states.
    enum PSDD_State {
        STATE_PASS,
        STATE_FAIL
    };

    /// @enum PSDD_Color
    ///
    /// Example enumeration of colors.
    enum PSDD_Color {
        COLOR_RED,
        COLOR_GREEN,
        COLOR_BLUE
    };

    /// @typedef BoundedString
    ///
    /// Bounded string of size 511 ASCII characters plus a NULL terminator.
    /// Bounded strings must have typedef before use in a struct. The default
    /// length of a string is 255 characters plus a terminator.
    typedef string<512> BoundedString;
};

#endif // CX_PORTS__PSDDPUBSUB__SNA_EXAMPLES_PSDD_DEFN_IDL

/// @}
//==============================================================================
//                            U N C L A S S I F I E D                            
//==============================================================================
