//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
// Copyright (c) Northrop Grumman Corporation 2020 -- ALL RIGHTS RESERVED
//==============================================================================
//
//==============================================================================
// EXPORT REGULATIONS (EAR99)
//==============================================================================
// DISCLOSURE: 
//
// Warning - This data is subject to the Export Administration Act (Title 22 
// U.S.C. App. 2401 et seq.), as amended. The implementing regulation for 
// this statute is the Export Administration Regulations (EAR) (15 C.F.R.
// 730-774). It may not be transferred, either in its original form, derivative 
// documents, or after being incorporated into other data without first 
// obtaining approval from the U.S. government or as otherwise authorized by 
// U.S. law and regulations. 
//==============================================================================
/// @defgroup SNA_Examples_PSDD_TestData_conn TestData_conn
/// @{
/// 
/// @file SNA_Examples_PSDD_TestData_conn.idl
/// @brief TestData_conn connector definition IDL file

//=========================================================

#ifndef CX_PORTS__PSDDPUBSUB__SNA_EXAMPLES_PSDD_TESTDATA_CONN_IDL
#define CX_PORTS__PSDDPUBSUB__SNA_EXAMPLES_PSDD_TESTDATA_CONN_IDL

#include <ccm_psdd.idl>
#include "SNA_Examples_PSDD_TestData_msg.idl"
#pragma ciao lem "SNA_Examples_PSDD_TestData_connE.idl"

/// @brief SNA_Examples_PSDD 
module SNA_Examples_PSDD {

    /// @typedef TestData_msgSeq
    ///
    /// Sequence of top-level message of type SNA_Examples::PSDD_TestData_msg to
    /// use with the DDS4CCM templated module instantiation.
    typedef sequence <TestData_msg> TestData_msgSeq;

    /// @var TestData_conn
    ///
    /// Templated Module Instantiation
    module CCM_PSDD::Typed <TestData_msg, TestData_msgSeq> TestData_conn; 
};

#endif // CX_PORTS__PSDDPUBSUB__SNA_EXAMPLES_PSDD_TESTDATA_CONN_IDL

/// @}
//==============================================================================
//                            U N C L A S S I F I E D                            
//==============================================================================
