//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
// Copyright (c) Northrop Grumman Corporation 2010 -- ALL RIGHTS RESERVED
//==============================================================================
/**
 * @defgroup WeatherStation_comp WeatherStation_comp Component
 * @ingroup WeatherExample
 * @{
 * The WeatherStation_comp component subscribes to temperature readings and
 * provides a capability for clients to query stats on these readings.
 * It performs the following activities:
 *    - Subscribes / Processes temperature readings
 *    - Creates a database containing the last 100 readings and a running
 *      average.
 *    - Provides a facet to allow clients to query the latest reading and the
 *      average over the last 100 temperature readings.
 * @file    SNA_Examples_WeatherStation_comp.idl
 * @brief   WeatherStation_comp component definition IDL file.
 */

//==============================================================================

#ifndef SNA_EXAMPLES_WEATHERSTATION_COMP_IDL
#define SNA_EXAMPLES_WEATHERSTATION_COMP_IDL

#include <Components.idl>

#include "SNA_Examples_TemperatureReading_conn.idl"
#include "SNA_Examples_WeatherInformation_obj.idl"

module SNA_Examples
{
   /**
    * This component listens to one type of DDS sample/message
    * (SNA_Examples::TemperatureReading_msg) and provides the weather 
    * information facet.
    */
   component WeatherStation_comp
   {
      /**
       * A DDS4CCM write port which publishes samples/messages of type
       * SNA_Examples::TemperatureReading_msg into a DDS topic. The name and 
       * QoS of that topic are defined in the deployment plan.
       * 
       * The DDS_StateListen port has callbacks for DDS instance create, update,
       * and deletion. A DDS instance is a set of samples corresponding to a key
       * value. The concept is very similar to rows in a database.
       * 
       * In this example, the key is the sensor ID (see the msg IDL).
       */
      port SNA_Examples::TemperatureReading_conn::DDS_StateListen 
                                                   temperatureReadingSub;

      /**
       * An optional CCM facet defined as part of the DDS4CCM standard which
       * the DDS4CCM connector can call on status changes (such as errors).
       *
       * This facet is recommended in most cases as it is useful for debugging
       * and integration.
       * 
       * It is recommended to have one of these provides lines for each
       * DDS4CCM extended port and to have them named after the associated port
       * name.
       */
      provides CCM_DDS::ConnectorStatusListener    temperatureReadingConnStatus;
      
      /**
       * This component provides the WeatherInformation facet which allows
       * other components to connect and query the weather station for
       * weather information.
       */
      provides SNA_Examples::WeatherInformation_obj weatherInformationFacet;
   };
};

#endif // SNA_EXAMPLES_WEATHERSTATION_COMP_IDL

/// @}
//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
