package CF.ExecutableDevicePackage;

/**
* CF/ExecutableDevicePackage/InvalidFunctionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/

public final class InvalidFunctionHolder implements org.omg.CORBA.portable.Streamable
{
  public CF.ExecutableDevicePackage.InvalidFunction value = null;

  public InvalidFunctionHolder ()
  {
  }

  public InvalidFunctionHolder (CF.ExecutableDevicePackage.InvalidFunction initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CF.ExecutableDevicePackage.InvalidFunctionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CF.ExecutableDevicePackage.InvalidFunctionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CF.ExecutableDevicePackage.InvalidFunctionHelper.type ();
  }

}
