/*
 * generated by Xtext
 */
package com.zeligsoft.domain.omg.corba.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IDLRuntimeModule extends com.zeligsoft.domain.omg.corba.dsl.AbstractIDLRuntimeModule {

}
