/// @defgroup AGSP_PCIP_Cmd_obj PCIP_Cmd_obj
/// @{
/// 
/// @file AGSP_PCIP_Cmd_obj.idl
/// @brief PCIP_Cmd_obj interface definition IDL file

//=========================================================

#ifndef CX_PORTS__POINTCLICKMODE__AGSP_PCIP_CMD_OBJ_IDL
#define CX_PORTS__POINTCLICKMODE__AGSP_PCIP_CMD_OBJ_IDL

#pragma ciao lem "AGSP_PCIP_Cmd_objE.idl"

/// @brief AGSP 
module AGSP {

    ///@interface PCIP_Cmd_obj 
    interface PCIP_Cmd_obj {

        void getStatus();
    };

};

#endif // CX_PORTS__POINTCLICKMODE__AGSP_PCIP_CMD_OBJ_IDL

/// @}

