//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
// Copyright (c) Northrop Grumman Corporation 2010 -- ALL RIGHTS RESERVED
//==============================================================================
/**
 * @defgroup TemperatureSensor_comp TemperatureSensor_comp Component
 * @ingroup WeatherExample
 * @{
 * The TemperatureSensor_comp component publishes temperature readings via a
 * DDS topic.
 * It performs the following activities:
 *    - Simulates a temperature reading
 *    - Publishes that reading on a DDS topic
 * @file    SNA_Examples_TemperatureSensor_comp.idl
 * @brief   TemperatureSensor_comp component definition IDL file.
 */

//==============================================================================

#ifndef SNA_EXAMPLES_TEMPERATURESENSOR_COMP_IDL
#define SNA_EXAMPLES_TEMPERATURESENSOR_COMP_IDL

#include <Components.idl>

#include "SNA_Examples_TemperatureReading_conn.idl"

module SNA_Examples
{
   /**
    * This component publishes one type of DDS sample/message
    * (SNA_Examples::TemperatureReading_msg).
    */
   component TemperatureSensor_comp
   {
      /**
       * A DDS4CCM write port which publishes samples/messages of type
       * SNA_Examples::TemperatureReading_msg into a DDS topic. The name and 
       * QoS of that topic are defined in the deployment plan.
       * 
       * The DDS_Update port has methods for DDS instance create, update,
       * and deletion. A DDS instance is a set of samples corresponding to a key
       * value. The concept is very similar to rows in a database.
       * 
       * In this example, the key is the sensor ID (see the msg IDL).
       */
      port SNA_Examples::TemperatureReading_conn::DDS_Update 
                                                       temperatureReadingPub;

      /**
       * An optional CCM facet defined as part of the DDS4CCM standard which
       * the DDS4CCM connector can call on status changes (such as errors).
       *
       * This facet is recommended in most cases as it is useful for debugging
       * and integration.
       * 
       * It is recommended to have one of these provides lines for each
       * DDS4CCM extended port and to have them named after the associated port
       * name.
       */
      provides CCM_DDS::ConnectorStatusListener temperatureReadingConnStatus;
      
      /**
       * attribute for the average simulated temperature 
       * NOTE: defaults to 24 degrees celsius
       */
      attribute double averageTemperature;
      
      /**
       * standard deviation to apply to the simulated temperature
       * NOTE: defaults to 3 degrees celsius
       */
      attribute long   stdDeviation;
   };
};

#endif // SNA_EXAMPLES_TEMPERATURESENSOR_COMP_IDL

/// @}
//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
