package CF.FileManagerPackage;

/**
* CF/FileManagerPackage/MountTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/

public final class MountTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public CF.FileManagerPackage.MountType value = null;

  public MountTypeHolder ()
  {
  }

  public MountTypeHolder (CF.FileManagerPackage.MountType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CF.FileManagerPackage.MountTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CF.FileManagerPackage.MountTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CF.FileManagerPackage.MountTypeHelper.type ();
  }

}
