package CF.FileManagerPackage;

/**
* CF/FileManagerPackage/NonExistentMountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/

public final class NonExistentMountHolder implements org.omg.CORBA.portable.Streamable
{
  public CF.FileManagerPackage.NonExistentMount value = null;

  public NonExistentMountHolder ()
  {
  }

  public NonExistentMountHolder (CF.FileManagerPackage.NonExistentMount initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CF.FileManagerPackage.NonExistentMountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CF.FileManagerPackage.NonExistentMountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CF.FileManagerPackage.NonExistentMountHelper.type ();
  }

}
