package CF.PortPackage;

/**
* CF/PortPackage/InvalidPortHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/

public final class InvalidPortHolder implements org.omg.CORBA.portable.Streamable
{
  public CF.PortPackage.InvalidPort value = null;

  public InvalidPortHolder ()
  {
  }

  public InvalidPortHolder (CF.PortPackage.InvalidPort initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CF.PortPackage.InvalidPortHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CF.PortPackage.InvalidPortHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CF.PortPackage.InvalidPortHelper.type ();
  }

}
