package CF.LoadableDevicePackage;

/**
* CF/LoadableDevicePackage/InvalidLoadKindHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/

public final class InvalidLoadKindHolder implements org.omg.CORBA.portable.Streamable
{
  public CF.LoadableDevicePackage.InvalidLoadKind value = null;

  public InvalidLoadKindHolder ()
  {
  }

  public InvalidLoadKindHolder (CF.LoadableDevicePackage.InvalidLoadKind initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CF.LoadableDevicePackage.InvalidLoadKindHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CF.LoadableDevicePackage.InvalidLoadKindHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CF.LoadableDevicePackage.InvalidLoadKindHelper.type ();
  }

}
