package CF.LoadableDevicePackage;


/**
* CF/LoadableDevicePackage/LoadTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/


/* This LoadType defines the type of load to be performed.
             The load types are in accordance with the code element within
             the softpkg element's implementation element. */
abstract public class LoadTypeHelper
{
  private static String  _id = "IDL:CF/LoadableDevice/LoadType:1.0";

  public static void insert (org.omg.CORBA.Any a, CF.LoadableDevicePackage.LoadType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CF.LoadableDevicePackage.LoadType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (CF.LoadableDevicePackage.LoadTypeHelper.id (), "LoadType", new String[] { "KERNEL_MODULE", "DRIVER", "SHARED_LIBRARY", "EXECUTABLE"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CF.LoadableDevicePackage.LoadType read (org.omg.CORBA.portable.InputStream istream)
  {
    return CF.LoadableDevicePackage.LoadType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CF.LoadableDevicePackage.LoadType value)
  {
    ostream.write_long (value.value ());
  }

}
