package CF.LoadableDevicePackage;


/**
* CF/LoadableDevicePackage/LoadFail.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/

public final class LoadFail extends org.omg.CORBA.UserException
{
  public CF.ErrorNumberType errorNumber = null;
  public String msg = null;

  public LoadFail ()
  {
    super(LoadFailHelper.id());
  } // ctor

  public LoadFail (CF.ErrorNumberType _errorNumber, String _msg)
  {
    super(LoadFailHelper.id());
    errorNumber = _errorNumber;
    msg = _msg;
  } // ctor


  public LoadFail (String $reason, CF.ErrorNumberType _errorNumber, String _msg)
  {
    super(LoadFailHelper.id() + "  " + $reason);
    errorNumber = _errorNumber;
    msg = _msg;
  } // ctor

} // class LoadFail
