package CF.LoadableDevicePackage;


/**
* CF/LoadableDevicePackage/LoadType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/


/* This LoadType defines the type of load to be performed.
             The load types are in accordance with the code element within
             the softpkg element's implementation element. */
public class LoadType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static CF.LoadableDevicePackage.LoadType[] __array = new CF.LoadableDevicePackage.LoadType [__size];

  public static final int _KERNEL_MODULE = 0;
  public static final CF.LoadableDevicePackage.LoadType KERNEL_MODULE = new CF.LoadableDevicePackage.LoadType(_KERNEL_MODULE);
  public static final int _DRIVER = 1;
  public static final CF.LoadableDevicePackage.LoadType DRIVER = new CF.LoadableDevicePackage.LoadType(_DRIVER);
  public static final int _SHARED_LIBRARY = 2;
  public static final CF.LoadableDevicePackage.LoadType SHARED_LIBRARY = new CF.LoadableDevicePackage.LoadType(_SHARED_LIBRARY);
  public static final int _EXECUTABLE = 3;
  public static final CF.LoadableDevicePackage.LoadType EXECUTABLE = new CF.LoadableDevicePackage.LoadType(_EXECUTABLE);

  public int value ()
  {
    return __value;
  }

  public static CF.LoadableDevicePackage.LoadType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected LoadType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class LoadType
