package CF.LoadableDevicePackage;

/**
* CF/LoadableDevicePackage/LoadTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/


/* This LoadType defines the type of load to be performed.
             The load types are in accordance with the code element within
             the softpkg element's implementation element. */
public final class LoadTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public CF.LoadableDevicePackage.LoadType value = null;

  public LoadTypeHolder ()
  {
  }

  public LoadTypeHolder (CF.LoadableDevicePackage.LoadType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CF.LoadableDevicePackage.LoadTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CF.LoadableDevicePackage.LoadTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CF.LoadableDevicePackage.LoadTypeHelper.type ();
  }

}
