/*
 * generated by Xtext
 */
package org.eclipse.papyrus.uml.textedit.message.xtext.parser.antlr;

import org.eclipse.papyrus.uml.textedit.message.xtext.services.UmlMessageGrammarAccess;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import com.google.inject.Inject;

public class UmlMessageParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {

	@Inject
	private UmlMessageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}

	@Override
	protected org.eclipse.papyrus.uml.textedit.message.xtext.parser.antlr.internal.InternalUmlMessageParser createParser(XtextTokenStream stream) {
		return new org.eclipse.papyrus.uml.textedit.message.xtext.parser.antlr.internal.InternalUmlMessageParser(stream, getGrammarAccess());
	}

	@Override
	protected String getDefaultRuleName() {
		return "MessageRule";
	}

	public UmlMessageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UmlMessageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}

}
