<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="oclstdlib" nsURI="http://www.eclipse.org/ocl/2015/Library" nsPrefix="oclstdlib">
  <eAnnotations source="http://www.eclipse.org/OCL/ASLibrary"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bag" instanceClassName="org.eclipse.ocl.pivot.values.Bag"
      abstract="true" interface="true">
    <eTypeParameters name="T"/>
    <eGenericSuperTypes eClassifier="#//Collection">
      <eTypeArguments eTypeParameter="#//Bag/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="java.lang.Boolean"/>
  <eClassifiers xsi:type="ecore:EClass" name="Collection" instanceClassName="java.util.Collection"
      abstract="true" interface="true">
    <eTypeParameters name="T"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" lowerBound="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Evaluates to the type of the collection elements.&#xA;&#xA;@Deprecated Use regular CollectionType property&#xA;"/>
      </eAnnotations>
      <eGenericType eTypeParameter="#//Collection/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" lowerBound="1" eType="#//Integer">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Evaluates to the lower bound on the number of collection elements.&#xA;&#xA;@Deprecated Use regular CollectionType property&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" lowerBound="1" eType="#//Integer">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Evaluates to the upper bound on the number of collection elements.&#xA;&#xA;@Deprecated Use regular CollectionType property&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="org.eclipse.ocl.pivot.values.IntegerValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="Map" instanceClassName="java.util.Map"
      abstract="true" interface="true">
    <eTypeParameters name="K"/>
    <eTypeParameters name="V"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyType" lowerBound="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The key type of the key-value pairs of oclText[self].&#xA;&#xA;@Deprecated Use regular MapType property&#xA;"/>
      </eAnnotations>
      <eGenericType eTypeParameter="#//Map/K"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueType" lowerBound="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The value type of the key-value pairs of oclText[self].&#xA;&#xA;@Deprecated Use regular MapType property&#xA;"/>
      </eAnnotations>
      <eGenericType eTypeParameter="#//Map/V"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OclAny" instanceClassName="java.lang.Object"
      abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This Ecore representation of the pivot OclAny exists solely to support serialization of Ecore metamodels.&#xA;True functionality is only available once converted to a Pivot model."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OclComparable" instanceClassName="java.lang.Object"
      abstract="true" interface="true" eSuperTypes="#//OclAny"/>
  <eClassifiers xsi:type="ecore:EClass" name="OclElement" instanceClassName="java.lang.Object"
      abstract="true" interface="true" eSuperTypes="#//OclAny">
    <eStructuralFeatures xsi:type="ecore:EReference" name="oclContainer" eType="#//OclElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The object for which self is a composed content or null if there is no such object.&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oclContents" ordered="false"
        upperBound="-1" eType="#//OclElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The composed contents of self."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OclEnumeration" instanceClassName="java.lang.Object"
      abstract="true" interface="true" eSuperTypes="#//OclAny"/>
  <eClassifiers xsi:type="ecore:EClass" name="OclInvalid" instanceClassName="java.lang.Object"
      abstract="true" interface="true" eSuperTypes="#//OclVoid">
    <eStructuralFeatures xsi:type="ecore:EReference" name="oclBadProperty" eType="#//OclAny">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An oclBadProperty may be used as a placeholder in an unsuccessfully created OCLExpression."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OclLambda" instanceClassName="java.lang.Object"
      abstract="true" interface="true" eSuperTypes="#//OclAny"/>
  <eClassifiers xsi:type="ecore:EClass" name="OclMessage" instanceClassName="java.lang.Object"
      abstract="true" interface="true" eSuperTypes="#//OclAny"/>
  <eClassifiers xsi:type="ecore:EClass" name="OclSelf" instanceClassName="java.lang.Object"
      abstract="true" interface="true" eSuperTypes="#//OclAny"/>
  <eClassifiers xsi:type="ecore:EClass" name="OclState" instanceClassName="java.lang.Object"
      abstract="true" interface="true" eSuperTypes="#//OclAny"/>
  <eClassifiers xsi:type="ecore:EClass" name="OclStereotype" instanceClassName="java.lang.Object"
      abstract="true" interface="true" eSuperTypes="#//OclType"/>
  <eClassifiers xsi:type="ecore:EClass" name="OclSummable" instanceClassName="java.lang.Object"
      abstract="true" interface="true" eSuperTypes="#//OclAny"/>
  <eClassifiers xsi:type="ecore:EClass" name="OclTuple" instanceClassName="java.lang.Object"
      abstract="true" interface="true" eSuperTypes="#//OclAny"/>
  <eClassifiers xsi:type="ecore:EClass" name="OclType" instanceClassName="java.lang.Object"
      abstract="true" interface="true" eSuperTypes="#//OclElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="OclVoid" instanceClassName="java.lang.Object"
      abstract="true" interface="true" eSuperTypes="#//OclAny"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrderedCollection" instanceClassName="java.util.Collection"
      abstract="true" interface="true">
    <eTypeParameters name="T"/>
    <eGenericSuperTypes eClassifier="#//Collection">
      <eTypeArguments eTypeParameter="#//OrderedCollection/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderedSet" instanceClassName="org.eclipse.ocl.pivot.values.OrderedSet"
      abstract="true" interface="true">
    <eTypeParameters name="T"/>
    <eGenericSuperTypes eClassifier="#//OrderedCollection">
      <eTypeArguments eTypeParameter="#//OrderedSet/T"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//UniqueCollection">
      <eTypeArguments eTypeParameter="#//OrderedSet/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Real" instanceClassName="org.eclipse.ocl.pivot.values.RealValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence" instanceClassName="java.util.List"
      abstract="true" interface="true">
    <eTypeParameters name="T"/>
    <eGenericSuperTypes eClassifier="#//OrderedCollection">
      <eTypeArguments eTypeParameter="#//Sequence/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Set" instanceClassName="java.util.Set"
      abstract="true" interface="true">
    <eTypeParameters name="T"/>
    <eGenericSuperTypes eClassifier="#//UniqueCollection">
      <eTypeArguments eTypeParameter="#//Set/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="UniqueCollection" instanceClassName="java.util.Collection"
      abstract="true" interface="true">
    <eTypeParameters name="T"/>
    <eGenericSuperTypes eClassifier="#//Collection">
      <eTypeArguments eTypeParameter="#//UniqueCollection/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="UnlimitedNatural" instanceClassName="org.eclipse.ocl.pivot.values.UnlimitedNaturalValue"/>
</ecore:EPackage>
