/// @defgroup AGSP_SystemManager_comp SystemManager_comp
/// @{
/// 
/// @file AGSP_SystemManager_comp.idl
/// @brief SystemManager_comp component definition IDL file

//=========================================================

#ifndef CX_COMPONENTS__SYSTEMMANAGER_COMP__SRC__AGSP_SYSTEMMANAGER_COMP_IDL
#define CX_COMPONENTS__SYSTEMMANAGER_COMP__SRC__AGSP_SYSTEMMANAGER_COMP_IDL

#include <Components.idl>
#pragma ciao lem "AGSP_SystemManager_compE.idl"
#pragma ami4ccm receptacle "AGSP::SystemManager_comp::CameraControlRecept"
#pragma ami4ccm receptacle "AGSP::SystemManager_comp::StateControlRecept"
#include "AGSP_CameraControl_obj.idl"
#include "AGSP_GimbalControl_obj.idl"
#include "AGSP_ModeControl_obj.idl"
#include "AGSP_StateControl_obj.idl"
#include "AGSP_ExtCommands_obj.idl"
#include "AGSP_SystemStatus_conn.idl"
#include "AGSP_AuxSensorStatus_conn.idl"
#include "AGSP_GPS_conn.idl"
#include "AGSP_ScheduleStatus_conn.idl"
#include "AGSP_Targets_conn.idl"

/// @namespace AGSP 
module AGSP {

    /// The SystemManager_comp component provides overall, centralized control
    /// for an instance of the SurveillanceProcessor_asm assembly.
    component SystemManager_comp {

        /// Client port used to control the camera when needed
        uses AGSP::CameraControl_obj CameraControlRecept;
        uses AGSP::GimbalControl_obj GimbalControlRecept;

        /// Client control port for controlling the camera modes
        uses AGSP::ModeControl_obj ModeControlRecept;
        uses multiple AGSP::StateControl_obj StateControlRecept;
        provides AGSP::ExtCommands_obj ExtCommandsFacet;

        /// Publisher port for system status info
        port SystemStatus_conn::DDS_Write SystemStatusPub;
        port AuxSensorStatus_conn::DDS_Listen AuxSensorStatusSub;
        port GPS_conn::DDS_Listen GPS_Sub;
        port ScheduleStatus_conn::DDS_StateListen ScheduleStatusSub;
        port ScheduleStatus_conn::DDS_Read ScheduleStatusSub2;
        port Targets_conn::DDS_Listen TargetsSub;
    };

};

#endif // CX_COMPONENTS__SYSTEMMANAGER_COMP__SRC__AGSP_SYSTEMMANAGER_COMP_IDL

/// @}

