//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
// Copyright (c) Northrop Grumman Corporation 2010 -- ALL RIGHTS RESERVED
//==============================================================================

/**
 * @defgroup Adapter_comp Adapter_comp Component
 * @ingroup ExternalAdaptorExample
 * @{
 *
 * The Adapter_comp component can be thought of as a translator in this example.
 * It interfaces with an external object through a TCP socket and is also the
 * client of the external server. It accepts TCP events from the socket and
 * passes the message on to the RelayServer_comp component through a CORBA
 * interface.
 *
 * @file   SNA_Examples_Adapter_comp.idl
 * @brief  Adapter_comp component definition IDL file.
 */

//==============================================================================

#ifndef SNA_EXAMPLES_ADAPTER_COMP_IDL
#define SNA_EXAMPLES_ADAPTER_COMP_IDL

// EXAMPLE:
// Components.idl is required for idl3 types
#include <Components.idl>

#include "SNA_Examples_RelayServer_obj.idl"

// EXAMPLE:
// the module keyword specifies a namespace for the Adapter_comp
module SNA_Examples
{
   /**
    * This component uses (calls) one CORBA interface/service.
    */
   component Adapter_comp
   {
      uses SNA_Examples::RelayServer_obj relayServerRecept; 
   };
};

#endif // SNA_EXAMPLES_ADAPTER_COMP_IDL

/// @}
//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
