/// @defgroup AGSP_ModeUtilities_comp ModeUtilities_comp
/// @{
/// 
/// @file AGSP_ModeUtilities_comp.idl
/// @brief ModeUtilities_comp component definition IDL file

//=========================================================

#ifndef CX_COMPONENTS__MODEUTILITIES_COMP__SRC__AGSP_MODEUTILITIES_COMP_IDL
#define CX_COMPONENTS__MODEUTILITIES_COMP__SRC__AGSP_MODEUTILITIES_COMP_IDL

#include <Components.idl>
#pragma ciao lem "AGSP_ModeUtilities_compE.idl"
#include "AGSP_ModeUtilities_obj.idl"

/// @namespace AGSP 
module AGSP {
    component ModeUtilities_comp {
        provides AGSP::ModeUtilities_obj ModeUtilitiesFacet;
    };

};

#endif // CX_COMPONENTS__MODEUTILITIES_COMP__SRC__AGSP_MODEUTILITIES_COMP_IDL

/// @}

