#ifndef CX_BASICSUBSCRIBER_COMP__SRC__SNA_EXAMPLES_BASICSUBSCRIBER_COMP_IDL
#define CX_BASICSUBSCRIBER_COMP__SRC__SNA_EXAMPLES_BASICSUBSCRIBER_COMP_IDL

#include <Components.idl>
#include "SNA_Examples_TestData_conn.idl"
#include <ccm_dds.idl>

module SNA_Examples {
    component BasicSubscriber_comp {
        port TestData_conn::DDS_Listen testDatSub;
        provides CCM_DDS::ConnectorStatusListener testDataSubConnStatus;
    };

};

#endif
