//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
// Copyright (c) Northrop Grumman Corporation 2008-2019 -- ALL RIGHTS RESERVED
//==============================================================================
/// @defgroup SNA_Examples_TestData_conn TestData_conn
/// @{
/// 
/// @file SNA_Examples_TestData_conn.idl
/// @brief TestData_conn connector definition IDL file

//=========================================================

#ifndef CX_PORTS__BASICPUBSUB__SNA_EXAMPLES_TESTDATA_CONN_IDL
#define CX_PORTS__BASICPUBSUB__SNA_EXAMPLES_TESTDATA_CONN_IDL

#include <Components.idl>
#include <ccm_dds.idl>
#include "SNA_Examples_TestData_msg.idl"
#pragma ciao lem "SNA_Examples_TestData_connE.idl"

/// @brief SNA_Examples 
module SNA_Examples {

    /// @typedef TestData_msgSeq
    ///
    /// Sequence of top-level message of type SNA_Examples::TestData_msg to use
    /// with the DDS4CCM templated module instantiation.
    typedef sequence <TestData_msg> TestData_msgSeq;

    /// @var TestData_conn
    ///
    /// Template module instantiation
    module CCM_DDS::Typed <TestData_msg, TestData_msgSeq> TestData_conn; 
};

#endif // CX_PORTS__BASICPUBSUB__SNA_EXAMPLES_TESTDATA_CONN_IDL

/// @}
//==============================================================================
//                            U N C L A S S I F I E D                            
//==============================================================================
