/// @defgroup AGSP_LS_Status_msg LS_Status_msg
/// @{
/// 
/// @file AGSP_LS_Status_msg.idl
/// @brief LS_Status_msg message definition IDL file

//=========================================================

#ifndef CX_PORTS__LIGHTSENSOR__AGSP_LS_STATUS_MSG_IDL
#define CX_PORTS__LIGHTSENSOR__AGSP_LS_STATUS_MSG_IDL

#include "AGSP_HSManager_defn.idl"
#pragma ndds typesupport "AGSP_LS_Status_msgSupport.h"

/// @brief AGSP 
module AGSP {

    /// @struct LS_Status_msg
    struct LS_Status_msg {
        AGSP::SensorStatus lightSensorStatus;
    }; //@top-level true
};

#endif // CX_PORTS__LIGHTSENSOR__AGSP_LS_STATUS_MSG_IDL

/// @}

