/// @defgroup AGSP_LS_Status_conn LS_Status_conn
/// @{
/// 
/// @file AGSP_LS_Status_conn.idl
/// @brief LS_Status_conn connector definition IDL file

//=========================================================

#ifndef CX_PORTS__LIGHTSENSOR__AGSP_LS_STATUS_CONN_IDL
#define CX_PORTS__LIGHTSENSOR__AGSP_LS_STATUS_CONN_IDL

#include <Components.idl>
#include <ccm_dds.idl>
#include "AGSP_LS_Status_msg.idl"
#pragma ciao lem "AGSP_LS_Status_connE.idl"

/// @brief AGSP 
module AGSP {

    /// @typedef LS_Status_msgSeq
    typedef sequence <LS_Status_msg> LS_Status_msgSeq;
    module CCM_DDS::Typed <LS_Status_msg, LS_Status_msgSeq> LS_Status_conn; 
};

#endif // CX_PORTS__LIGHTSENSOR__AGSP_LS_STATUS_CONN_IDL

/// @}

