//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
// Copyright (c) Northrop Grumman Corporation 2010 -- ALL RIGHTS RESERVED
//==============================================================================
/// @addtogroup PubSubClientServer_comp
/// @{
/// @file   SNA_Examples_NumAssert_msg.idl
/// @brief  Definition of DDS message used in the PubSubClientServer example.
//==============================================================================

#ifndef SNA_EXAMPLES_NUMASSERT_MSG_IDL
#define SNA_EXAMPLES_NUMASSERT_MSG_IDL

#pragma ndds typesupport "SNA_Examples_NumAssert_msgSupport.h"

module SNA_Examples
{  
   /**
    * @struct NumAssert_msg
    *
    * DDS message structure for the number assertion message.
    */
   struct NumAssert_msg
   {
      /**
       * True if number is valid, false otherwise.
       */
      boolean numValid;
   }; //@top-level true
};

#endif // SNA_EXAMPLES_NUMASSERT_MSG_IDL

/// @}
//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
