//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
// Copyright (c) Northrop Grumman Corporation 2010 -- ALL RIGHTS RESERVED
//==============================================================================
/// @addtogroup Echo_comp
/// @{
/// @file   SNA_Examples_EchoAssert_obj.idl
/// @brief  Definition of number assertion CORBA interface.
//==============================================================================

#ifndef SNA_EXAMPLES_ECHOASSERT_OBJ_IDL
#define SNA_EXAMPLES_ECHOASSERT_OBJ_IDL

#pragma ciao lem "SNA_Examples_EchoAssert_objE.idl"

// the module keyword is similar to "namespace" in c++
module SNA_Examples
{
   // interface keyword is similar to "class" in c++
   
   /**
    * @interface EchoAssert_obj
    *
    * Number assertion CORBA interface used by the PubSubClientServer example. 
    * 
    * @note This interface could be used with other components or with a
    * regular CORBA application. It is not tied to CCM.
    * 
    * @note Components which "provide" this interface will need to implement the
    * method(s) in it. 
    */
   interface EchoAssert_obj
   {
      /**
       * Access number assertion.
       * @return true if number is valid, false otherwise
       */
      boolean getNumAssert();
   };
};

#endif // SNA_EXAMPLES_ECHOASSERT_OBJ_IDL

/// @}
//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================

