/// @defgroup AGSP_PC_ImageProcessing_comp PC_ImageProcessing_comp
/// @{
/// 
/// @file AGSP_PC_ImageProcessing_comp.idl
/// @brief PC_ImageProcessing_comp component definition IDL file

//=========================================================

#ifndef CX_COMPONENTS__PC_IMAGEPROCESSING_COMP__SRC__AGSP_PC_IMAGEPROCESSING_COMP_IDL
#define CX_COMPONENTS__PC_IMAGEPROCESSING_COMP__SRC__AGSP_PC_IMAGEPROCESSING_COMP_IDL

#include <Components.idl>
#pragma ciao lem "AGSP_PC_ImageProcessing_compE.idl"
#include "AGSP_PCPC_Status_obj.idl"
#include "AGSP_PCIP_Cmd_obj.idl"
#include "AGSP_Images_conn.idl"
#include "AGSP_UnprocessedImages_conn.idl"

/// @namespace AGSP 
module AGSP {

    /// The PC_ImageProcessing_comp subscribes to all incoming raw images output
    /// from camera.  it performs a set of image processing operations on each
    /// received image, according to the last set of operations commanded by
    /// PC_PictureControl_comp via its service control port.  When completed,
    /// each processed & formatted image is published on its output publisher
    /// port for dissemination.
    component PC_ImageProcessing_comp {
        uses AGSP::PCPC_Status_obj PCPC_StatusRecept;
        provides AGSP::PCIP_Cmd_obj PCIP_CmdFacet;
        port Images_conn::PSAT_Write ImagesPub;
        port UnprocessedImages_conn::PSAT_Listen UnprocessedImagesSub;
    };

};

#endif // CX_COMPONENTS__PC_IMAGEPROCESSING_COMP__SRC__AGSP_PC_IMAGEPROCESSING_COMP_IDL

/// @}

