/// @defgroup AGSP_CamIntCmd_obj CamIntCmd_obj
/// @{
/// 
/// @file AGSP_CamIntCmd_obj.idl
/// @brief CamIntCmd_obj interface definition IDL file

//=========================================================

#ifndef CX_SURVEILLANCEPROCESSOR_ASM__CAMERASCHEDULER_ASM__SCHEDULERSTATUS_COMP__PORTS__AGSP_CAMINTCMD_OBJ_IDL
#define CX_SURVEILLANCEPROCESSOR_ASM__CAMERASCHEDULER_ASM__SCHEDULERSTATUS_COMP__PORTS__AGSP_CAMINTCMD_OBJ_IDL

#pragma ciao lem "AGSP_CamIntCmd_objE.idl"

/// @namespace AGSP 
module AGSP {

    ///@interface CamIntCmd_obj 
    interface CamIntCmd_obj {

        void getStatus();
    };

};

#endif // CX_SURVEILLANCEPROCESSOR_ASM__CAMERASCHEDULER_ASM__SCHEDULERSTATUS_COMP__PORTS__AGSP_CAMINTCMD_OBJ_IDL

/// @}

