/// @defgroup AGSP_Targets_conn Targets_conn
/// @{
/// 
/// @file AGSP_Targets_conn.idl
/// @brief Targets_conn connector definition IDL file

//=========================================================

#ifndef CX_PORTS__3CAMERAMODES__AGSP_TARGETS_CONN_IDL
#define CX_PORTS__3CAMERAMODES__AGSP_TARGETS_CONN_IDL

#include <Components.idl>
#include <ccm_dds.idl>
#include "AGSP_Targets_msg.idl"
#pragma ciao lem "AGSP_Targets_connE.idl"

/// @namespace AGSP 
module AGSP {

    /// @typedef Targets_msgSeq
    typedef sequence <Targets_msg> Targets_msgSeq;
    module CCM_DDS::Typed <Targets_msg, Targets_msgSeq> Targets_conn; 
};

#endif // CX_PORTS__3CAMERAMODES__AGSP_TARGETS_CONN_IDL

/// @}

