//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
// Copyright (c) Northrop Grumman Corporation 2010 -- ALL RIGHTS RESERVED
//==============================================================================

/**
 * @defgroup PSAT_Subscriber_comp PSAT_Subscriber_comp Component
 * @ingroup PSAT_Example
 * @{
 *
 * The PSAT_Subscriber_comp component is the subscriber in this example. It
 * subscribes to a topic using PSAT (Publish/Subscribe Attachment Transfer).
 * When a sample is published to the topic, this component is notified and it
 * reads and logs a portion of the message.
 *
 * @file   SNA_Examples_PSAT_Subscriber_comp.idl
 * @brief  PSAT_Subscriber_comp component definition IDL file.
 */

//==============================================================================

#ifndef SNA_EXAMPLES_PSAT_SUBSCRIBER_COMP_IDL
#define SNA_EXAMPLES_PSAT_SUBSCRIBER_COMP_IDL

#include <Components.idl>

#include "SNA_Examples_PSAT_Example_UDM_conn.idl"

module SNA_Examples
{
   /**
    * This component subscribes using pub-sub attachment transfer (PSAT).
    */
   component PSAT_Subscriber_comp
   {
      // PSAT_Listen (subscribing) port which uses a custom UDM (metadata
      // structure).
      port SNA_Examples::PSAT_Example_UDM_conn::PSAT_Listen numArraySub;
      
      /**
       * An optional CCM facet defined as part of the DDS4CCM standard which
       * the PSAT connector can call on status changes (such as errors).
       *
       * This facet is recommended in most cases as it is useful for debugging
       * and integration.
       * 
       * It is recommended to have one of these provides lines for each
       * DDS4CCM extended port and to have them named after the associated port
       * name.
       */
      provides CCM_DDS::ConnectorStatusListener numArraySubConnStatus;
   };
};

#endif // SNA_EXAMPLES_PSAT_SUBSCRIBER_COMP_IDL

/// @}
//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
