/// @defgroup SNA_Examples_TestData_msg TestData_msg
/// @{
/// 
/// @file SNA_Examples_TestData_msg.idl
/// @brief TestData_msg message definition IDL file

//=========================================================

#ifndef CX_BASICPUBLISHER_COMP__PORTS__SNA_EXAMPLES_TESTDATA_MSG_IDL
#define CX_BASICPUBLISHER_COMP__PORTS__SNA_EXAMPLES_TESTDATA_MSG_IDL

#include "SNA_Examples_defn.idl"
#pragma ndds typesupport "SNA_Examples_TestData_msgSupport.h"

/// @namespace SNA_Examples 
module SNA_Examples {

    /// @struct TestData_msg
    ///
    /// // This is my message
    struct TestData_msg {
        unsigned long myInt32;
        unsigned long long myInt64;
        double myDouble;
        SNA_Examples::BoundedString myString;
        SNA_Examples::State myState;

        /// // This is an enum
        SNA_Examples::Color myColor;
    }; //@top-level true
};

#endif // CX_BASICPUBLISHER_COMP__PORTS__SNA_EXAMPLES_TESTDATA_MSG_IDL

/// @}

