//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
// Copyright (c) Northrop Grumman Corporation 2010 -- ALL RIGHTS RESERVED
//==============================================================================
/// @addtogroup TemperatureSensor_comp
/// @{
/// @file   SNA_Examples_TemperatureReading_msg.idl
/// @brief  Definition of DDS message used in the Weather example.
//==============================================================================

#ifndef SNA_EXAMPLES_TEMPERATURE_READING_MSG_IDL
#define SNA_EXAMPLES_TEMPERATURE_READING_MSG_IDL

#pragma ndds typesupport "SNA_Examples_TemperatureReading_msgSupport.h"

module SNA_Examples
{
   /**
    * @struct TemperatureReading_msg
    *
    * Example DDS message structure for a temperature reading used in the
    * Weather example.
    */
   struct TemperatureReading_msg
   {
      /**
       * The temperature reading in degrees celsius
       */
      double temperature;
      
      /**
       * ID of the temperature sensor which gave this reading
       */
      long   sensorId; //@key
   }; //@top-level true
};

#endif // SNA_EXAMPLES_TEMPERATURE_READING_MSG_IDL

/// @}
//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
