package CF;


/**
* CF/_LifeCycleStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/


/* The LifeCycle interface defines the generic operations for
         initializing or releasing instantiated component-specific
         data and/or processing elements. */
public class _LifeCycleStub extends org.omg.CORBA.portable.ObjectImpl implements CF.LifeCycle
{


  /* The purpose of the initialize operation is to provide a mechanism
               to set an object to an known initial state. */
  public void initialize () throws CF.LifeCyclePackage.InitializeError
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("initialize", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:CF/LifeCycle/InitializeError:1.0"))
                    throw CF.LifeCyclePackage.InitializeErrorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                initialize (        );
            } finally {
                _releaseReply ($in);
            }
  } // initialize


  /* The purpose of the releaseObject operation is to provide a means
               by which an instantiated component may be torn down. */
  public void releaseObject () throws CF.LifeCyclePackage.ReleaseError
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("releaseObject", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:CF/LifeCycle/ReleaseError:1.0"))
                    throw CF.LifeCyclePackage.ReleaseErrorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                releaseObject (        );
            } finally {
                _releaseReply ($in);
            }
  } // releaseObject

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CF/LifeCycle:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _LifeCycleStub
