package CF;


/**
* CF/_TestableObjectStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/


/* The TestableObject interface defines a set of operations that
         can be used to test component implementations.  */
public class _TestableObjectStub extends org.omg.CORBA.portable.ObjectImpl implements CF.TestableObject
{


  /* The runTest operation allows components to be "blackbox" tested.
               This allows Built-In Tests to be implemented which
               provides a means to isolate faults (both software and hardware)
               within the system. */
  public void runTest (int testid, CF.PropertiesHolder testValues) throws CF.TestableObjectPackage.UnknownTest, CF.UnknownProperties
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("runTest", true);
                $out.write_ulong (testid);
                CF.PropertiesHelper.write ($out, testValues.value);
                $in = _invoke ($out);
                testValues.value = CF.PropertiesHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:CF/TestableObject/UnknownTest:1.0"))
                    throw CF.TestableObjectPackage.UnknownTestHelper.read ($in);
                else if (_id.equals ("IDL:CF/UnknownProperties:1.0"))
                    throw CF.UnknownPropertiesHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                runTest (testid, testValues        );
            } finally {
                _releaseReply ($in);
            }
  } // runTest

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CF/TestableObject:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _TestableObjectStub
