package CF;


/**
* CF/AggregateDevice.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:34 PM EDT
*/


/* The AggregateDevice interface provides aggregate behavior that can be
         used to add and remove Devices from a parent device.  This interface
         can be provided via inheritance or as a "provides port". Child devices
         use this interface to add or remove themselves from parent device when
         being created or torn-down. */
public interface AggregateDevice extends AggregateDeviceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AggregateDevice
