package CF;


/**
* CF/ApplicationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/


/* The Application interface provides for the control, configuration,
         and status of an instantiated application in the domain. */
public interface ApplicationOperations  extends CF.ResourceOperations
{

  /* This attribute contains the list of components'
               Naming Service Context within the Application for those
               components using CORBA Naming Service.  */
  CF.ApplicationPackage.ComponentElementType[] componentNamingContexts ();

  /* This attribute contains the list of components' process IDs within
               the Application for components that are executing on a device. */
  CF.ApplicationPackage.ComponentProcessIdType[] componentProcessIds ();

  /* The componentDevices attribute contain a list of devices
               which each component either uses, is loaded on or is executed on.
               Each component (componentinstantiation element in the Application's
               software profile) is associated with a device.  */
  CF.DeviceAssignmentType[] componentDevices ();

  /* This attribute contains the list of components' SPD implementation
               IDs within the Application for those components created.  */
  CF.ApplicationPackage.ComponentElementType[] componentImplementations ();

  /* This attribute is the XML profile information for the application.
               The string value contains  a profile element with a file
               reference to the SAD. */
  String profile ();

  /* This name attribute contains the name of the created Application.
               The ApplicationFactory interfaces's create operation name parameter
               provides the name content.  */
  String name ();
} // interface ApplicationOperations
