package CF;


/**
* CF/DeviceAssignmentType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:34 PM EDT
*/

public final class DeviceAssignmentType implements org.omg.CORBA.portable.IDLEntity
{
  public String componentId = null;
  public String assignedDeviceId = null;

  public DeviceAssignmentType ()
  {
  } // ctor

  public DeviceAssignmentType (String _componentId, String _assignedDeviceId)
  {
    componentId = _componentId;
    assignedDeviceId = _assignedDeviceId;
  } // ctor

} // class DeviceAssignmentType
