package CF;


/**
* CF/Device.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/


/* The Device interface defines additional capabilities and attributes 
	     for any logical Device in the domain.  */
public interface Device extends DeviceOperations, CF.Resource, org.omg.CORBA.portable.IDLEntity 
{
} // interface Device
