package CF;

/**
* CF/FileSystemHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:34 PM EDT
*/


/* The FileSystem interface defines the CORBA operations to enable
         remote access to a physical file system.  */
public final class FileSystemHolder implements org.omg.CORBA.portable.Streamable
{
  public CF.FileSystem value = null;

  public FileSystemHolder ()
  {
  }

  public FileSystemHolder (CF.FileSystem initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CF.FileSystemHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CF.FileSystemHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CF.FileSystemHelper.type ();
  }

}
