package CF;


/**
* CF/FileManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/


/* Multiple, distributed FileSystems may be accessed through
         a FileManager. The FileManager interface appears to be a single
         FileSystem although the actual file storage may span multiple
         physical file systems. */
public interface FileManagerOperations  extends CF.FileSystemOperations
{

  /* The mount operation associates a FileSystem with a mount
  		     point (a directory name). */
  void mount (String mountPoint, CF.FileSystem file_System) throws CF.InvalidFileName, CF.FileManagerPackage.InvalidFileSystem, CF.FileManagerPackage.MountPointAlreadyExists;

  /* The unmount operation removes a mounted FileSystem from the
               FileManager whose mounted name matches the input mountPoint
               name. */
  void unmount (String mountPoint) throws CF.FileManagerPackage.NonExistentMount;

  /* The getMounts operation returns the FileManager's
               mounted FileSystems. */
  CF.FileManagerPackage.MountType[] getMounts ();
} // interface FileManagerOperations
