package CF;


/**
* CF/InvalidProfile.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:34 PM EDT
*/

public final class InvalidProfile extends org.omg.CORBA.UserException
{

  public InvalidProfile ()
  {
    super(InvalidProfileHelper.id());
  } // ctor


  public InvalidProfile (String $reason)
  {
    super(InvalidProfileHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidProfile
