package CF;

/**
* CF/InvalidObjectReferenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:34 PM EDT
*/

public final class InvalidObjectReferenceHolder implements org.omg.CORBA.portable.Streamable
{
  public CF.InvalidObjectReference value = null;

  public InvalidObjectReferenceHolder ()
  {
  }

  public InvalidObjectReferenceHolder (CF.InvalidObjectReference initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CF.InvalidObjectReferenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CF.InvalidObjectReferenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CF.InvalidObjectReferenceHelper.type ();
  }

}
