package CF;


/**
* CF/InvalidFileName.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:34 PM EDT
*/

public final class InvalidFileName extends org.omg.CORBA.UserException
{
  public CF.ErrorNumberType errorNumber = null;
  public String msg = null;

  public InvalidFileName ()
  {
    super(InvalidFileNameHelper.id());
  } // ctor

  public InvalidFileName (CF.ErrorNumberType _errorNumber, String _msg)
  {
    super(InvalidFileNameHelper.id());
    errorNumber = _errorNumber;
    msg = _msg;
  } // ctor


  public InvalidFileName (String $reason, CF.ErrorNumberType _errorNumber, String _msg)
  {
    super(InvalidFileNameHelper.id() + "  " + $reason);
    errorNumber = _errorNumber;
    msg = _msg;
  } // ctor

} // class InvalidFileName
