package CF;


/**
* CF/InvalidObjectReference.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:34 PM EDT
*/

public final class InvalidObjectReference extends org.omg.CORBA.UserException
{
  public String msg = null;

  public InvalidObjectReference ()
  {
    super(InvalidObjectReferenceHelper.id());
  } // ctor

  public InvalidObjectReference (String _msg)
  {
    super(InvalidObjectReferenceHelper.id());
    msg = _msg;
  } // ctor


  public InvalidObjectReference (String $reason, String _msg)
  {
    super(InvalidObjectReferenceHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class InvalidObjectReference
