package CF;

/**
* CF/InvalidFileNameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:34 PM EDT
*/

public final class InvalidFileNameHolder implements org.omg.CORBA.portable.Streamable
{
  public CF.InvalidFileName value = null;

  public InvalidFileNameHolder ()
  {
  }

  public InvalidFileNameHolder (CF.InvalidFileName initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CF.InvalidFileNameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CF.InvalidFileNameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CF.InvalidFileNameHelper.type ();
  }

}
