package CF;


/**
* CF/LoadableDevice.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/


/* This interface extends the Device interface by adding
         software loading and unloading behavior to a Device.  */
public interface LoadableDevice extends LoadableDeviceOperations, CF.Device, org.omg.CORBA.portable.IDLEntity 
{
} // interface LoadableDevice
