package CF;


/**
* CF/OctetSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:34 PM EDT
*/


/* This type is a CORBA unbounded sequence of octets. */
public final class OctetSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public OctetSequenceHolder ()
  {
  }

  public OctetSequenceHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CF.OctetSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CF.OctetSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CF.OctetSequenceHelper.type ();
  }

}
