package CF;


/**
* CF/PropertySetHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/


/* The PropertySet interface defines configure and query operations
         to access component properties/attributes.  */
abstract public class PropertySetHelper
{
  private static String  _id = "IDL:CF/PropertySet:1.0";

  public static void insert (org.omg.CORBA.Any a, CF.PropertySet that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CF.PropertySet extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CF.PropertySetHelper.id (), "PropertySet");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CF.PropertySet read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PropertySetStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CF.PropertySet value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CF.PropertySet narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CF.PropertySet)
      return (CF.PropertySet)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CF._PropertySetStub stub = new CF._PropertySetStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CF.PropertySet unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CF.PropertySet)
      return (CF.PropertySet)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CF._PropertySetStub stub = new CF._PropertySetStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
