package CF.ApplicationPackage;


/**
* CF/ApplicationPackage/ComponentElementType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/

public final class ComponentElementType implements org.omg.CORBA.portable.IDLEntity
{
  public String componentId = null;
  public String elementId = null;

  public ComponentElementType ()
  {
  } // ctor

  public ComponentElementType (String _componentId, String _elementId)
  {
    componentId = _componentId;
    elementId = _elementId;
  } // ctor

} // class ComponentElementType
