package CF.ApplicationPackage;


/**
* CF/ApplicationPackage/ComponentProcessIdSequenceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/


/* The ComponentProcessIdSequence type defines an unbounded sequence
             of components' process IDs.  */
abstract public class ComponentProcessIdSequenceHelper
{
  private static String  _id = "IDL:CF/Application/ComponentProcessIdSequence:1.0";

  public static void insert (org.omg.CORBA.Any a, CF.ApplicationPackage.ComponentProcessIdType[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CF.ApplicationPackage.ComponentProcessIdType[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = CF.ApplicationPackage.ComponentProcessIdTypeHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (CF.ApplicationPackage.ComponentProcessIdSequenceHelper.id (), "ComponentProcessIdSequence", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CF.ApplicationPackage.ComponentProcessIdType[] read (org.omg.CORBA.portable.InputStream istream)
  {
    CF.ApplicationPackage.ComponentProcessIdType value[] = null;
    int _len0 = istream.read_long ();
    value = new CF.ApplicationPackage.ComponentProcessIdType[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = CF.ApplicationPackage.ComponentProcessIdTypeHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CF.ApplicationPackage.ComponentProcessIdType[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      CF.ApplicationPackage.ComponentProcessIdTypeHelper.write (ostream, value[_i0]);
  }

}
