package CF.ApplicationPackage;


/**
* CF/ApplicationPackage/ComponentProcessIdSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/


/* The ComponentProcessIdSequence type defines an unbounded sequence
             of components' process IDs.  */
public final class ComponentProcessIdSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public CF.ApplicationPackage.ComponentProcessIdType value[] = null;

  public ComponentProcessIdSequenceHolder ()
  {
  }

  public ComponentProcessIdSequenceHolder (CF.ApplicationPackage.ComponentProcessIdType[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CF.ApplicationPackage.ComponentProcessIdSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CF.ApplicationPackage.ComponentProcessIdSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CF.ApplicationPackage.ComponentProcessIdSequenceHelper.type ();
  }

}
