package CF.ApplicationPackage;


/**
* CF/ApplicationPackage/ComponentProcessIdTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/

abstract public class ComponentProcessIdTypeHelper
{
  private static String  _id = "IDL:CF/Application/ComponentProcessIdType:1.0";

  public static void insert (org.omg.CORBA.Any a, CF.ApplicationPackage.ComponentProcessIdType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CF.ApplicationPackage.ComponentProcessIdType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "componentId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulong);
          _members0[1] = new org.omg.CORBA.StructMember (
            "processId",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (CF.ApplicationPackage.ComponentProcessIdTypeHelper.id (), "ComponentProcessIdType", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CF.ApplicationPackage.ComponentProcessIdType read (org.omg.CORBA.portable.InputStream istream)
  {
    CF.ApplicationPackage.ComponentProcessIdType value = new CF.ApplicationPackage.ComponentProcessIdType ();
    value.componentId = istream.read_string ();
    value.processId = istream.read_ulong ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CF.ApplicationPackage.ComponentProcessIdType value)
  {
    ostream.write_string (value.componentId);
    ostream.write_ulong (value.processId);
  }

}
