/// @defgroup AGSP_SchedulerServer_comp SchedulerServer_comp
/// @{
/// 
/// @file AGSP_SchedulerServer_comp.idl
/// @brief SchedulerServer_comp component definition IDL file

//=========================================================

#ifndef CX_COMPONENTS__SCHEDULERSERVER_COMP__SRC__AGSP_SCHEDULERSERVER_COMP_IDL
#define CX_COMPONENTS__SCHEDULERSERVER_COMP__SRC__AGSP_SCHEDULERSERVER_COMP_IDL

#include <Components.idl>
#pragma ciao lem "AGSP_SchedulerServer_compE.idl"
#include "AGSP_CamIntCmd_obj.idl"
#include "AGSP_CamIntStatus_obj.idl"
#include "AGSP_ModeControl_obj.idl"
#include "AGSP_ScheduleRequest_obj.idl"
#include "AGSP_StateControl_obj.idl"
#include "AGSP_ScheduleStatus_conn.idl"

/// @namespace AGSP 
module AGSP {
    component SchedulerServer_comp {
        uses AGSP::CamIntCmd_obj CamIntCmdRecept;
        provides AGSP::CamIntStatus_obj CamIntStatusFacet;
        provides AGSP::ModeControl_obj ModeControlFacet;
        provides AGSP::ScheduleRequest_obj ScheduleRequestFacet;
        provides AGSP::StateControl_obj StateControlFacet;
        port ScheduleStatus_conn::DDS_Update ScheduleStatusPub;
    };

};

#endif // CX_COMPONENTS__SCHEDULERSERVER_COMP__SRC__AGSP_SCHEDULERSERVER_COMP_IDL

/// @}

