/// @defgroup AGSP_ExtCommands_obj ExtCommands_obj
/// @{
/// 
/// @file AGSP_ExtCommands_obj.idl
/// @brief ExtCommands_obj interface definition IDL file

//=========================================================

#ifndef CX_PORTS__2SURVEILLANCEPROCESSOR__AGSP_EXTCOMMANDS_OBJ_IDL
#define CX_PORTS__2SURVEILLANCEPROCESSOR__AGSP_EXTCOMMANDS_OBJ_IDL

#include "AGSP_Common_defn.idl"
#pragma ciao lem "AGSP_ExtCommands_objE.idl"
#pragma ami4ccm interface "AGSP::ExtCommands_obj"
#pragma ciao lem "AGSP_ExtCommands_objAE.idl"
#pragma ami4ccm idl "AGSP_ExtCommands_objA.idl"

/// @namespace AGSP 
module AGSP {

    ///@interface ExtCommands_obj 
    interface ExtCommands_obj {

        /// @param[in] newState
        ///
        /// @return
        AGSP::ReturnStatus changeState(
            in AGSP::SystemState newState
            );

        /// @return
        AGSP::SystemState getCurrentState();

        /// @param[in] newMode
        ///
        /// @return
        AGSP::ReturnStatus setMode(
            in AGSP::SystemMode newMode
            );

        /// @return
        AGSP::SystemMode getCurrentMode();
    };

};

#endif // CX_PORTS__2SURVEILLANCEPROCESSOR__AGSP_EXTCOMMANDS_OBJ_IDL

/// @}

