/// @defgroup AGSP_AuxSensorStatus_conn AuxSensorStatus_conn
/// @{
/// 
/// @file AGSP_AuxSensorStatus_conn.idl
/// @brief AuxSensorStatus_conn connector definition IDL file

//=========================================================

#ifndef CX_PORTS__2SURVEILLANCEPROCESSOR__AGSP_AUXSENSORSTATUS_CONN_IDL
#define CX_PORTS__2SURVEILLANCEPROCESSOR__AGSP_AUXSENSORSTATUS_CONN_IDL

#include <Components.idl>
#include <ccm_dds.idl>
#include "AGSP_AuxSensorStatus_msg.idl"
#pragma ciao lem "AGSP_AuxSensorStatus_connE.idl"

/// @namespace AGSP 
module AGSP {

    /// @typedef AuxSensorStatus_msgSeq
    typedef sequence <AuxSensorStatus_msg> AuxSensorStatus_msgSeq;
    module CCM_DDS::Typed <AuxSensorStatus_msg, AuxSensorStatus_msgSeq> AuxSensorStatus_conn; 
};

#endif // CX_PORTS__2SURVEILLANCEPROCESSOR__AGSP_AUXSENSORSTATUS_CONN_IDL

/// @}

