/// @defgroup AGSP_HumanTrackerMode_comp HumanTrackerMode_comp
/// @{
/// 
/// @file AGSP_HumanTrackerMode_comp.idl
/// @brief HumanTrackerMode_comp component definition IDL file

//=========================================================

#ifndef CX_COMPONENTS__HUMANTRACKERMODE_COMP__SRC__AGSP_HUMANTRACKERMODE_COMP_IDL
#define CX_COMPONENTS__HUMANTRACKERMODE_COMP__SRC__AGSP_HUMANTRACKERMODE_COMP_IDL

#include <Components.idl>
#pragma ciao lem "AGSP_HumanTrackerMode_compE.idl"
#pragma ami4ccm receptacle "AGSP::HumanTrackerMode_comp::CameraControlRecept"
#include "AGSP_CameraControl_obj.idl"
#include "AGSP_GimbalControl_obj.idl"
#include "AGSP_ModeUtilities_obj.idl"
#include "AGSP_ScheduleRequest_obj.idl"
#include "AGSP_StateControl_obj.idl"
#include "AGSP_Images_conn.idl"
#include "AGSP_Targets_conn.idl"
#include "AGSP_CameraAvailable_conn.idl"
#include "AGSP_GPS_conn.idl"
#include "AGSP_ScheduleStatus_conn.idl"
#include "AGSP_UnprocessedImages_conn.idl"

/// @namespace AGSP 
module AGSP {
    component HumanTrackerMode_comp {
        uses AGSP::CameraControl_obj CameraControlRecept;
        uses AGSP::GimbalControl_obj GimbalControlRecept;
        uses AGSP::ModeUtilities_obj ModeUtilitiesRecept;
        uses AGSP::ScheduleRequest_obj ScheduleRequestRecept;
        provides AGSP::StateControl_obj StateControlFacet;
        port Images_conn::PSAT_Write ImagesPub;
        port Targets_conn::DDS_Write TargetsPub;
        port CameraAvailable_conn::DDS_Listen CameraAvailableSub;
        port GPS_conn::DDS_Listen GPS_Sub;
        port ScheduleStatus_conn::DDS_StateListen ScheduleStatusSub;
        port UnprocessedImages_conn::PSAT_Listen UnprocessedImagesSub;
    };

};

#endif // CX_COMPONENTS__HUMANTRACKERMODE_COMP__SRC__AGSP_HUMANTRACKERMODE_COMP_IDL

/// @}

