package com.prismtech.domain.sca.ppls.utils;

public interface VPMImages {
	
	public static final String ICON_FOLDER_FULL_OBJ16 = "full/obj16/"; //$NON-NLS-1$
	
	public static final String ICON_FOLDER_FULL_CTOOL16 = "full/ctool16/"; //$NON-NLS-1$
	
	public static final String VARIATION_POINT__IMAGE = ICON_FOLDER_FULL_OBJ16 + VPMNames.VARIATION_POINT;
	
	public static final String VARIATION_POINT_WITH_VALUE__IMAGE = ICON_FOLDER_FULL_OBJ16 + VPMNames.VARIATION_POINT_WITH_VALUE;

	public static final String VARIATION_POINT_WITH_SETTINGS__IMAGE = ICON_FOLDER_FULL_OBJ16 + VPMNames.VARIATION_POINT_WITH_SETTINGS;
	
	public static final String CONSTRAINED_ELEMENT__IMAGE = ICON_FOLDER_FULL_OBJ16 + VPMNames.CONSTRAINED_ELEMENT;
	
	public static final String ATTRIBUTE__IMAGE = ICON_FOLDER_FULL_OBJ16 + VPMNames.ATTRIBUTE;
	
	public static final String CONFIGURATION__IMAGE = ICON_FOLDER_FULL_OBJ16 + VPMNames.CONFIGURATION;
		
	public static final String CONFIGURATION_POINT__IMAGE = ICON_FOLDER_FULL_OBJ16 + VPMNames.CONFIGURATION_POINT;
	
	public static final String BOOLEAN_VALUE__IMAGE = ICON_FOLDER_FULL_OBJ16 + "BooleanValue"; //$NON-NLS-1$
	
	public static final String GENERIC_VALUE__IMAGE = ICON_FOLDER_FULL_OBJ16 + "GenericValue"; //$NON-NLS-1$
	
	public static final String CONFIGURATION_POINT_WITH_VALUE__IMAGE = ICON_FOLDER_FULL_OBJ16 + VPMNames.CONFIGURATION_POINT_WITH_VALUE;
	
	public static final String CONFIGURATION_POINT_WITH_SETTINGS__IMAGE = ICON_FOLDER_FULL_OBJ16 + VPMNames.CONFIGURATION_POINT_WITH_SETTINGS;
	
	public static final String SETTABLE_ATTTRIBUTE__IMAGE = ICON_FOLDER_FULL_OBJ16 + VPMNames.SETTABLE_ATTTRIBUTE;
	
	public static final String VPMODEL__IMAGE = ICON_FOLDER_FULL_OBJ16 + VPMNames.VPMODEL;
	
}
