// Parameters of all basic types

interface int1056
{
      void func1
        (
          inout string returnString,
          inout short returnShort,
          in long returnLong,
          out long long returnLongLong, 
          out unsigned short returnUnsignedShort, 
          out unsigned long returnUnsignedLong,
          in unsigned long long returnUnsignedLongLong, 
          inout float returnFloat, 
          out double returnDouble,
          in long double returnLongDouble,
          in char returnChar,
          inout wchar returnWChar,
          out boolean returnBoolean,
          in octet returnOctet,
          inout any returnAny
        );
};

