// Interface with a wide variety of return types.

interface int1043
{
  void returnVoid ();
  string returnString ();
  short returnShort();
  long returnLong();
  long long returnLongLong();
  unsigned short returnUnsignedShort();
  unsigned long returnUnsignedLong();
  unsigned long long returnUnsignedLongLong();
  float returnFloat();
  double returnDouble();
  long double returnLongDouble();
  char returnChar();
  wchar returnWChar();
  boolean returnBoolean();
  octet returnOctet();
};