typedef string stringType;
typedef short shortType;
typedef long longType;
typedef long long longLongType;
typedef unsigned short unsignedShortType;
typedef unsigned long unsignedLongType;
typedef unsigned long long unsignedLongLongType;
typedef float floatType;
typedef double doubleType;
typedef long double longDoubleType;
typedef char charType;
typedef wchar wCharType;
typedef boolean booleanType;
typedef octet octetType;
typedef any anyType;

interface int1036 {

attribute stringType i_am_a_string;
attribute shortType i_am_a_short;
attribute longType i_am_a_long;
attribute longLongType i_am_a_long_long;
attribute unsignedShortType i_am_an_unsigned_short;
attribute unsignedLongType i_am_an_unsigned_long;
attribute unsignedLongLongType i_am_an_unsigned_long_long;
attribute floatType i_am_a_float;
attribute doubleType i_am_a_double;
attribute longDoubleType i_am_a_long_double;
attribute charType i_am_a_char;
attribute wCharType i_am_a_wchar;
attribute booleanType i_am_a_bool;
attribute octetType i_am_an_octet;
attribute anyType i_am_an_any;

};