// Complex parameter types

interface int1057
{
      struct s1 { long a; };
      enum e1 { VALUE };
      union u1 switch (long) { default: float a; };

      void func1 ( in s1 structparam, out e1 enumparam, inout u1 unionparam );
};