// All possible directions

interface int1054
{
      void inparam ( in unsigned short par1
        );
      void outparam ( out string par2
        );
      void inoutparam ( inout float par3
        );

};