/// @defgroup AGSP_UnprocessedImages_msg UnprocessedImages_msg
/// @{
/// 
/// @file AGSP_UnprocessedImages_msg.idl
/// @brief UnprocessedImages_msg message definition IDL file

//=========================================================

#ifndef CX_SURVEILLANCEPROCESSOR_ASM__CAMERADATAADAPTER_COMP__PORTS__AGSP_UNPROCESSEDIMAGES_MSG_IDL
#define CX_SURVEILLANCEPROCESSOR_ASM__CAMERADATAADAPTER_COMP__PORTS__AGSP_UNPROCESSEDIMAGES_MSG_IDL

#include "ccm_psat_header_defn.idl"
#include "AGSP_UnprocessedImages_defn.idl"
#pragma ndds typesupport "AGSP_UnprocessedImages_msgSupport.h"

/// @namespace AGSP 
module AGSP {

    /// @struct UnprocessedImages_msg
    struct UnprocessedImages_msg {
        CCM_PSAT::PSAT_Header psat_hdr;
        long long xPixels;
        long long yPixels;
        AGSP::PixArray pixData;
    }; //@top-level true
};

#endif // CX_SURVEILLANCEPROCESSOR_ASM__CAMERADATAADAPTER_COMP__PORTS__AGSP_UNPROCESSEDIMAGES_MSG_IDL

/// @}

