/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.zeligsoft.domain.omg.corba.dsl.idl.validation;


/**
 * A sample validator interface for {@link com.zeligsoft.domain.omg.corba.dsl.idl.Interface_or_Forward_Decl}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface Interface_or_Forward_DeclValidator {
	boolean validate();

}
