/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.zeligsoft.domain.omg.corba.dsl.idl.validation;

import com.zeligsoft.domain.omg.corba.dsl.idl.Preproc_If_Val;

/**
 * A sample validator interface for {@link com.zeligsoft.domain.omg.corba.dsl.idl.Preproc_If_Compare}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface Preproc_If_CompareValidator {
	boolean validate();

	boolean validateLhs(Preproc_If_Val value);
	boolean validateOp(String value);
	boolean validateRhs(Preproc_If_Val value);
}
