//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
// Copyright (c) Northrop Grumman Corporation 2010 -- ALL RIGHTS RESERVED
//==============================================================================

/**
 * @defgroup  BasicSubscriber_comp BasicSubscriber_comp Component
 * @ingroup BasicPubSubExample
 * @{
 * The BasicSubscriber_comp component is the subscriber in this example. It
 * subscribes to a DDS topic. When a sample is published to that topic, this
 * component is notified, and it reads the sample (message), and logs it.
 *
 * @file    SNA_Examples_BasicSubscriber_comp.idl
 * @brief   BasicSubscriber_comp component definition IDL file.
 */

//==============================================================================

#ifndef SNA_EXAMPLES_BASICSUBSCRIBER_COMP_IDL
#define SNA_EXAMPLES_BASICSUBSCRIBER_COMP_IDL

#include <Components.idl>

#include "SNA_Examples_TestData_conn.idl"

module SNA_Examples
{
   /**
    * This component subscribes to one type of DDS sample/message
    * (SNA_Examples::TestData_msg).
    */
   component BasicSubscriber_comp
   {
      /**
       * A DDS4CCM listen port which listens for samples/messages of type
       * SNA_Examples::TestData_msg on a DDS topic. The name and QoS of that
       * topic are defined in the deployment plan.
       */
      port SNA_Examples::TestData_conn::DDS_Listen testDataSub;

      /**
       * An optional CCM facet defined as part of the DDS4CCM standard which
       * the DDS4CCM connector can call on status changes (such as errors).
       *
       * This facet is recommended in most cases as it is useful for debugging
       * and integration.
       * 
       * It is recommended to have one of these provides lines for each
       * DDS4CCM extended port and to have them named after the associated port
       * name.
       */
      provides CCM_DDS::ConnectorStatusListener    testDataSubConnStatus;
   };
};

#endif // SNA_EXAMPLES_BASICSUBSCRIBER_COMP_IDL

/// @}
//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
