package LogService;


/**
* LogService/_LogStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LogService.idl
* Monday, May 4, 2009 2:19:36 PM EDT
*/


/* A Log is utilized by CF and CORBA capable application components to
		   store
		   informational messages. These informational messages are referred to as
		   log records in this document. The interface provides operations for
		   writing
		   log records to a Log, retrieving LogRecords from a Log, controlling of a
		   Log,
		   and getting the status of a Log. */
public class _LogStub extends org.omg.CORBA.portable.ObjectImpl implements LogService.Log
{


  /* This operation provides the maximum number of bytes that the Log
  				   can store.
  				   The getMaxSizeis operation returns the integer number of bytes that
  				   the Log is capable of storing.
  				   This operation does not raise any exceptions.
  				   @roseuid 3B268C6203B5 */
  public long getMaxSize ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getMaxSize", true);
                $in = _invoke ($out);
                long $result = $in.read_ulonglong ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getMaxSize (        );
            } finally {
                _releaseReply ($in);
            }
  } // getMaxSize


  /* This operation sets the maximum number of bytes that the Log can
  				   store.
  				   The setMaxSize operation sets the maximum size of the log measured
  				   in number of bytes.
  				   This operation does not return a value.
  				   The setMaxSize operation raises the InvalidParam exception if the
  				   size parameter passed
  				   in is less than the current size of the Log.
  				   The setMaxSizeis operation raises the InvalidParam exception if the
  				   size parameter passed
  				   in is less than the current size of the Log
  				   @roseuid 3B268CAF0207 */
  public void setMaxSize (long size) throws LogService.LogPackage.InvalidParam
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setMaxSize", true);
                $out.write_ulonglong (size);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:LogService/Log/InvalidParam:1.0"))
                    throw LogService.LogPackage.InvalidParamHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setMaxSize (size        );
            } finally {
                _releaseReply ($in);
            }
  } // setMaxSize


  /* The getCurrentSize operation provides the current size of the
  				   log storage in bytes.
  				   The getCurrentSize operation returns the current size of the log
  				   storage in bytes
  				   (i.e. if the log contains no records, get CurrentSize will return a
  				   value of 0.).
  				   This operation does not return any exceptions.
  				   @roseuid 3B268D1500C4 */
  public long getCurrentSize ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getCurrentSize", true);
                $in = _invoke ($out);
                long $result = $in.read_ulonglong ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getCurrentSize (        );
            } finally {
                _releaseReply ($in);
            }
  } // getCurrentSize


  /* The getNumRecords operation provides the number of records
  				   present in the Log.
  				   The getNumRecords operation returns the current number of
  				   LogRecords contained in the Log.
  				   This operation does not raise any exceptions.
  				   @roseuid 3B268D2B00D9 */
  public long getNumRecords ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getNumRecords", true);
                $in = _invoke ($out);
                long $result = $in.read_ulonglong ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getNumRecords (        );
            } finally {
                _releaseReply ($in);
            }
  } // getNumRecords


  /* The getLogFullAction operation provides the action taken when
  				   the Log becomes full.
  				   The getLogFullAction operation returns the Logs full action
  				   setting.
  				   This operation does not return any exceptions.
  				   @roseuid 3B268D4603BD */
  public LogService.LogPackage.LogFullActionType getLogFullAction ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getLogFullAction", true);
                $in = _invoke ($out);
                LogService.LogPackage.LogFullActionType $result = LogService.LogPackage.LogFullActionTypeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getLogFullAction (        );
            } finally {
                _releaseReply ($in);
            }
  } // getLogFullAction


  /* The setLogFullAction operation provides the mechanism to
  				   configure the action taken by a Log when it becomes full.
  				   The setLogFullAction operation sets the action taken by a Log when
  				   its
  				   maximum size has been reached to the value specified in the action
  				   parameter.
  				   The valid values for the action parameter, WRAP and HALT, are
  				   described by LogFullActionType.
  				   This operation does not return a value.
  				   This operation does not return any exceptions.
  				   @roseuid 3B268D6503B8 */
  public void setLogFullAction (LogService.LogPackage.LogFullActionType action)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setLogFullAction", true);
                LogService.LogPackage.LogFullActionTypeHelper.write ($out, action);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setLogFullAction (action        );
            } finally {
                _releaseReply ($in);
            }
  } // setLogFullAction


  /* The getAvailabilityStatus operation is used to read the
  				   availability status of the Log.
  				   The getAvailabilityStatus operation returns the current
  				   availability status of the Log.
  				   This operation does not raise any exceptions.
  				   @roseuid 3B268DD302CF */
  public LogService.LogPackage.AvailabilityStatusType getAvailabilityStatus ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getAvailabilityStatus", true);
                $in = _invoke ($out);
                LogService.LogPackage.AvailabilityStatusType $result = LogService.LogPackage.AvailabilityStatusTypeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getAvailabilityStatus (        );
            } finally {
                _releaseReply ($in);
            }
  } // getAvailabilityStatus


  /* The getAdministrativeState is used to read the administrative
  				   state of the Log.
  				   The getAdministrativeState operation returns the current
  				   administrative state of the Log.
  				   This operation does not raise any exceptions.
  				   @roseuid 3B268DEC0376 */
  public LogService.LogPackage.AdministrativeStateType getAdministrativeState ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getAdministrativeState", true);
                $in = _invoke ($out);
                LogService.LogPackage.AdministrativeStateType $result = LogService.LogPackage.AdministrativeStateTypeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getAdministrativeState (        );
            } finally {
                _releaseReply ($in);
            }
  } // getAdministrativeState


  /* The setAdministrativeState operation provides write access to
  				   the administrative state value.
  				   The setAdministrativeState operation sets the administrative state of the Log.
  				   This operation does not return a value.
  				   This operation does not raise any exceptions.
  				   @roseuid 3B268E0503AE */
  public void setAdministrativeState (LogService.LogPackage.AdministrativeStateType state)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setAdministrativeState", true);
                LogService.LogPackage.AdministrativeStateTypeHelper.write ($out, state);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setAdministrativeState (state        );
            } finally {
                _releaseReply ($in);
            }
  } // setAdministrativeState


  /* The getOperationalState operation returns the operational state
  				   of the Log.
  				   This operation does not raise any exceptions.
  				   @roseuid 3B268F0B02D8 */
  public LogService.LogPackage.OperationalStateType getOperationalState ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getOperationalState", true);
                $in = _invoke ($out);
                LogService.LogPackage.OperationalStateType $result = LogService.LogPackage.OperationalStateTypeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getOperationalState (        );
            } finally {
                _releaseReply ($in);
            }
  } // getOperationalState


  /* The writeRecords operation provides the method for writing log
  				   records to the Log.
  				   The operation is defined as oneway to minimize client overhead
  				   while writing to the Log.
  				   The writeRecords operation adds each log record supplied in the
  				   records parameter to the Log.
  				   When there is insufficient storage to add one of the supplied log
  				   records
  				   to the Log, and the LogFullAction is set to HALT, the writeRecords
  				   method sets the availability
  				   status logFull state to true. (i.e. if 3 records are provided in
  				   the records parameter,
  				   and while trying to write the second record to the log, the record
  				   will not fit, then the
  				   Log is considered to be full therefore the second and third records
  				   will not be stored in the
  				   Log but the first record would have been successfully stored.).
  				   The writeRecords operation writes the current local time to the
  				   time field of each record written to the Log.
  				   The writeRecords operation assigns a unique record ID to the id
  				   field of the LogRecordlog record.
  				   Log records accepted for storage by the writeRecords are made
  				   available for retrieval in the order received.
  				   This operation does not return a value.
  				   This operation does not raise any exceptions.
  				   @roseuid 3B32456C03B8 */
  public void writeRecords (LogService.ProducerLogRecordType[] records)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("writeRecords", false);
                LogService.LogPackage.ProducerLogRecordSequenceHelper.write ($out, records);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                writeRecords (records        );
            } finally {
                _releaseReply ($in);
            }
  } // writeRecords


  /* The getRecordIDFromTime operation is used to get the record ID
  				   of the first record in the
  				   log with a time-stamp that is greater than, or equal to, the time
  				   specified in the parameter.
  				   The getRecordIdFromTime operation returns the record ID of the
  				   first record in the log with a time
  				   stamp that is greater than, or equal to, the time specified in the
  				   fromTime parameter. If the
  				   Log does not contain a record that meets the criteria provided,
  				   then the RecordIDType
  				   returned shall correspond to the next record that will be recorded
  				   in the future. In this way, if
  				   this "future" recordID is passed into the retrieveById operation,
  				   an empty record will be returned,
  				   unless since that time records have been recorded. Note that if
  				   the time specified in the fromTime
  				   parameter is in the future, there is no guarantee that the
  				   resulting records returned will have a time
  				   stamp after the fromTime parameter if the returned recordID is
  				   subsequently used as input to the retrieveByID operation.
  				   The getRecordIdFromTime operation returns the record ID of the
  				   first record in the log with a time stamp that
  				   is greater than, or equal to, the time specified in the fromTime
  				   parameter. If the Log does not contain a
  				   record that meets the criteria provided, then the RecordIDType
  				   returned corresponds to the next record that
  				   will be recorded in the future. In this way, if this "future"
  				   recordID is passed into the retrieveById operation,
  				   an empty record will be returned, unless since that time records
  				   have been recorded.
  				   This operation raises no exceptions.
  				   @roseuid 3B33581D02C4 */
  public long getRecordIdFromTime (LogService.LogPackage.LogTimeType fromTime)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRecordIdFromTime", true);
                LogService.LogPackage.LogTimeTypeHelper.write ($out, fromTime);
                $in = _invoke ($out);
                long $result = LogService.LogPackage.RecordIdTypeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRecordIdFromTime (fromTime        );
            } finally {
                _releaseReply ($in);
            }
  } // getRecordIdFromTime


  /* The retrieveById operation is used to get a specified number of
  				   records from a Log.
  				   The retrieveById operation returns a list of LogRecords that begins
  				   with the record specified by
  				   the currentID parameter and contains less than or equal to the
  				   number of records specified in the howMany parameter.
  				   The retrieveById operation sets the inout parameter currentId to
  				   the LogRecord Id of next record after
  				   the last record in the LogRecordSequence returned. If the record
  				   sequence returned exhausts the log records,
  				   then the currentId parameter sets the LogRecordId of where the log
  				   will resume writing logs on the next write.
  				   The retrieveById operation returns a LogRecordSequence that begins
  				   with the record specified by the
  				   currentId parameter. The number of records in the
  				   LogRecordSequencereturned by the retrieveById operation
  				   is equal to the number of records specified by the howMany
  				   parameter, or the number of records available if
  				   the number of records specified by the howMany parameter cannot be
  				   met. If the record specified by currentId
  				   does not exist, the retrieveById operation returns an empty list of
  				   LogRecords and leave the currentId unchanged.
  				   If the Log is empty, or has been exhausted, the retrieveById
  				   operation returns an empty list of LogRecords and
  				   leave the currentId unchanged.
  				   This operation does not raise any exceptions.
  				   @roseuid 3B32456D000C */
  public LogService.LogPackage.LogRecordType[] retrieveById (org.omg.CORBA.LongHolder currentId, int howMany)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("retrieveById", true);
                LogService.LogPackage.RecordIdTypeHelper.write ($out, currentId.value);
                $out.write_ulong (howMany);
                $in = _invoke ($out);
                LogService.LogPackage.LogRecordType $result[] = LogService.LogPackage.LogRecordSequenceHelper.read ($in);
                currentId.value = LogService.LogPackage.RecordIdTypeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return retrieveById (currentId, howMany        );
            } finally {
                _releaseReply ($in);
            }
  } // retrieveById


  /* The clearLog operation provides the method for removing all of
  				   the LogRecords from the Log.
  				   The clearLog operation deletes all records from the Log. The
  				   clearLog operation sets the current
  				   size of the Log storage to zero. The clearLog operation sets the
  				   current number of records in the
  				   Log to zero. The clearLog operation sets the logFull availability
  				   status element to false.
  				   The clearLog operation does not return a value.
  				   This operation does not raise any exceptions.
  				   @roseuid 3B32456D003E */
  public void clearLog ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("clearLog", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                clearLog (        );
            } finally {
                _releaseReply ($in);
            }
  } // clearLog


  /* The destroy operation provides a means by which an instantiated
  				   Log may be torn down.
  				   The destroy operation releases all internal memory and/or storage
  				   allocated by theLog.
  				   The destroy operation tears down the component (i.e. released from
  				   the CORBA environment).
  				   The destroy operation does not return a value.
  				   This operation does not raise any exceptions.
  				   @roseuid 3B32456D007A */
  public void destroy ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("destroy", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                destroy (        );
            } finally {
                _releaseReply ($in);
            }
  } // destroy

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:LogService/Log:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _LogStub
