package LogService;


/**
* LogService/Log.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LogService.idl
* Monday, May 4, 2009 2:19:36 PM EDT
*/


/* A Log is utilized by CF and CORBA capable application components to
		   store
		   informational messages. These informational messages are referred to as
		   log records in this document. The interface provides operations for
		   writing
		   log records to a Log, retrieving LogRecords from a Log, controlling of a
		   Log,
		   and getting the status of a Log. */
public interface Log extends LogOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Log
