package LogService;


/**
* LogService/LogLevelType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LogService.idl
* Monday, May 4, 2009 2:19:36 PM EDT
*/


/* The LogLevelType is an enumeration type that is utilized to identify
		   log levels. */
public class LogLevelType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 24;
  private static LogService.LogLevelType[] __array = new LogService.LogLevelType [__size];

  public static final int _FAILURE_ALARM = 0;
  public static final LogService.LogLevelType FAILURE_ALARM = new LogService.LogLevelType(_FAILURE_ALARM);
  public static final int _DEGRADED_ALRAM = 1;
  public static final LogService.LogLevelType DEGRADED_ALRAM = new LogService.LogLevelType(_DEGRADED_ALRAM);
  public static final int _EXCEPTION_ERROR = 2;
  public static final LogService.LogLevelType EXCEPTION_ERROR = new LogService.LogLevelType(_EXCEPTION_ERROR);
  public static final int _FLOW_CONTROL_ERROR = 3;
  public static final LogService.LogLevelType FLOW_CONTROL_ERROR = new LogService.LogLevelType(_FLOW_CONTROL_ERROR);
  public static final int _RANGE_ERROR = 4;
  public static final LogService.LogLevelType RANGE_ERROR = new LogService.LogLevelType(_RANGE_ERROR);
  public static final int _USAGE_ERROR = 5;
  public static final LogService.LogLevelType USAGE_ERROR = new LogService.LogLevelType(_USAGE_ERROR);
  public static final int _ADMINISTRATIVE_EVENT = 6;
  public static final LogService.LogLevelType ADMINISTRATIVE_EVENT = new LogService.LogLevelType(_ADMINISTRATIVE_EVENT);
  public static final int _STATISTIC_REPORT = 7;
  public static final LogService.LogLevelType STATISTIC_REPORT = new LogService.LogLevelType(_STATISTIC_REPORT);
  public static final int _PROGRAMMER_DEBUG1 = 8;
  public static final LogService.LogLevelType PROGRAMMER_DEBUG1 = new LogService.LogLevelType(_PROGRAMMER_DEBUG1);
  public static final int _PROGRAMMER_DEBUG2 = 9;
  public static final LogService.LogLevelType PROGRAMMER_DEBUG2 = new LogService.LogLevelType(_PROGRAMMER_DEBUG2);
  public static final int _PROGRAMMER_DEBUG3 = 10;
  public static final LogService.LogLevelType PROGRAMMER_DEBUG3 = new LogService.LogLevelType(_PROGRAMMER_DEBUG3);
  public static final int _PROGRAMMER_DEBUG4 = 11;
  public static final LogService.LogLevelType PROGRAMMER_DEBUG4 = new LogService.LogLevelType(_PROGRAMMER_DEBUG4);
  public static final int _PROGRAMMER_DEBUG5 = 12;
  public static final LogService.LogLevelType PROGRAMMER_DEBUG5 = new LogService.LogLevelType(_PROGRAMMER_DEBUG5);
  public static final int _PROGRAMMER_DEBUG6 = 13;
  public static final LogService.LogLevelType PROGRAMMER_DEBUG6 = new LogService.LogLevelType(_PROGRAMMER_DEBUG6);
  public static final int _PROGRAMMER_DEBUG7 = 14;
  public static final LogService.LogLevelType PROGRAMMER_DEBUG7 = new LogService.LogLevelType(_PROGRAMMER_DEBUG7);
  public static final int _PROGRAMMER_DEBUG8 = 15;
  public static final LogService.LogLevelType PROGRAMMER_DEBUG8 = new LogService.LogLevelType(_PROGRAMMER_DEBUG8);
  public static final int _PROGRAMMER_DEBUG9 = 16;
  public static final LogService.LogLevelType PROGRAMMER_DEBUG9 = new LogService.LogLevelType(_PROGRAMMER_DEBUG9);
  public static final int _PROGRAMMER_DEBUG10 = 17;
  public static final LogService.LogLevelType PROGRAMMER_DEBUG10 = new LogService.LogLevelType(_PROGRAMMER_DEBUG10);
  public static final int _PROGRAMMER_DEBUG11 = 18;
  public static final LogService.LogLevelType PROGRAMMER_DEBUG11 = new LogService.LogLevelType(_PROGRAMMER_DEBUG11);
  public static final int _PROGRAMMER_DEBUG12 = 19;
  public static final LogService.LogLevelType PROGRAMMER_DEBUG12 = new LogService.LogLevelType(_PROGRAMMER_DEBUG12);
  public static final int _PROGRAMMER_DEBUG13 = 20;
  public static final LogService.LogLevelType PROGRAMMER_DEBUG13 = new LogService.LogLevelType(_PROGRAMMER_DEBUG13);
  public static final int _PROGRAMMER_DEBUG14 = 21;
  public static final LogService.LogLevelType PROGRAMMER_DEBUG14 = new LogService.LogLevelType(_PROGRAMMER_DEBUG14);
  public static final int _PROGRAMMER_DEBUG15 = 22;
  public static final LogService.LogLevelType PROGRAMMER_DEBUG15 = new LogService.LogLevelType(_PROGRAMMER_DEBUG15);
  public static final int _PROGRAMMER_DEBUG16 = 23;
  public static final LogService.LogLevelType PROGRAMMER_DEBUG16 = new LogService.LogLevelType(_PROGRAMMER_DEBUG16);

  public int value ()
  {
    return __value;
  }

  public static LogService.LogLevelType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected LogLevelType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class LogLevelType
