package LogService;


/**
* LogService/LogLevelSequenceTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LogService.idl
* Monday, May 4, 2009 2:19:36 PM EDT
*/


/* The LogLevelSequence type is an unbounded sequence of LogLevelTypes.
		   The PRODUCER_LOG_LEVEL configure/query property is of the
		   LogLevelSequence type. */
public final class LogLevelSequenceTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public LogService.LogLevelType value[] = null;

  public LogLevelSequenceTypeHolder ()
  {
  }

  public LogLevelSequenceTypeHolder (LogService.LogLevelType[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LogService.LogLevelSequenceTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LogService.LogLevelSequenceTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LogService.LogLevelSequenceTypeHelper.type ();
  }

}
