package LogService;


/**
* LogService/LogLevelSequenceTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LogService.idl
* Monday, May 4, 2009 2:19:36 PM EDT
*/


/* The LogLevelSequence type is an unbounded sequence of LogLevelTypes.
		   The PRODUCER_LOG_LEVEL configure/query property is of the
		   LogLevelSequence type. */
abstract public class LogLevelSequenceTypeHelper
{
  private static String  _id = "IDL:LogService/LogLevelSequenceType:1.0";

  public static void insert (org.omg.CORBA.Any a, LogService.LogLevelType[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static LogService.LogLevelType[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = LogService.LogLevelTypeHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (LogService.LogLevelSequenceTypeHelper.id (), "LogLevelSequenceType", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static LogService.LogLevelType[] read (org.omg.CORBA.portable.InputStream istream)
  {
    LogService.LogLevelType value[] = null;
    int _len0 = istream.read_long ();
    value = new LogService.LogLevelType[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = LogService.LogLevelTypeHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, LogService.LogLevelType[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      LogService.LogLevelTypeHelper.write (ostream, value[_i0]);
  }

}
