/// @defgroup AGSP_Images_defn Images_defn
/// @{
/// 
/// @file AGSP_Images_defn.idl
/// @brief Images_defn definitions definition IDL file

//=========================================================

#ifndef CX_SURVEILLANCEPROCESSOR_ASM__CAMERAMODES_ASM__PORTS__AGSP_IMAGES_DEFN_IDL
#define CX_SURVEILLANCEPROCESSOR_ASM__CAMERAMODES_ASM__PORTS__AGSP_IMAGES_DEFN_IDL


/// @namespace AGSP 
module AGSP {

    /// @typedef IntImageArray
    typedef octet IntImageArray[63999-0+1];
};

#endif // CX_SURVEILLANCEPROCESSOR_ASM__CAMERAMODES_ASM__PORTS__AGSP_IMAGES_DEFN_IDL

/// @}

