<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="deployment"
    nsURI="http://www.zeligsoft.com/zdm/1.0.0" nsPrefix="zdm">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="TBD&#xD;&#xA;&#xD;&#xA;&#xD;&#xA;This will be harder"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Deployment" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//ENamedElement">
    <eOperations name="getDepth" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eOperations name="getAllDeploymentParts">
      <eGenericType eClassifier="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EEList">
        <eTypeArguments eClassifier="#//DeploymentPart"/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deploymentPart" ordered="false"
        upperBound="-1" eType="#//DeploymentPart" containment="true" eOpposite="#//DeploymentPart/deployment"
        eKeys="#//DeploymentPart/id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocation" ordered="false"
        upperBound="-1" eType="#//Allocation" containment="true" eOpposite="#//Allocation/deployment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeploymentPart" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//ENamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="not(self.sourceAllocation.targetPart = self)"/>
    </eAnnotations>
    <eOperations name="getContainingDeployment" eType="#//Deployment"/>
    <eOperations name="getPartDeployedOn" eType="#//DeploymentPart"/>
    <eOperations name="getDepth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getOldModelElement" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="configurationElement" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceAllocation" ordered="false"
        eType="#//Allocation" eOpposite="#//Allocation/sourcePart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetAllocation" ordered="false"
        upperBound="-1" eType="#//Allocation" eOpposite="#//Allocation/targetPart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentPart" ordered="false"
        eType="#//DeploymentPart" eOpposite="#//DeploymentPart/childPart" eKeys="#//DeploymentPart/id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childPart" ordered="false"
        upperBound="-1" eType="#//DeploymentPart" containment="true" eOpposite="#//DeploymentPart/parentPart"
        eKeys="#//DeploymentPart/id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployment" ordered="false"
        lowerBound="1" eType="#//Deployment" eOpposite="#//Deployment/deploymentPart"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        unsettable="true" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelElement" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Allocation" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPart" ordered="false"
        lowerBound="1" eType="#//DeploymentPart" eOpposite="#//DeploymentPart/targetAllocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployment" ordered="false"
        lowerBound="1" eType="#//Deployment" eOpposite="#//Deployment/allocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePart" ordered="false"
        lowerBound="1" eType="#//DeploymentPart" eOpposite="#//DeploymentPart/sourceAllocation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        unsettable="true" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeploymentComponentPart" eSuperTypes="#//DeploymentPart"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeploymentConnectorPart" eSuperTypes="#//DeploymentPart"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeploymentPortPart" eSuperTypes="#//DeploymentPart"/>
</ecore:EPackage>
