/// @defgroup AGSP_CameraAvailable_conn CameraAvailable_conn
/// @{
/// 
/// @file AGSP_CameraAvailable_conn.idl
/// @brief CameraAvailable_conn connector definition IDL file

//=========================================================

#ifndef CX_SURVEILLANCEPROCESSOR_ASM__CAMERACONTROLADAPTER_COMP__PORTS__AGSP_CAMERAAVAILABLE_CONN_IDL
#define CX_SURVEILLANCEPROCESSOR_ASM__CAMERACONTROLADAPTER_COMP__PORTS__AGSP_CAMERAAVAILABLE_CONN_IDL

#include <Components.idl>
#include <ccm_dds.idl>
#include "AGSP_CameraAvailable_msg.idl"
#pragma ciao lem "AGSP_CameraAvailable_connE.idl"

/// @namespace AGSP 
module AGSP {

    /// @typedef CameraAvailable_msgSeq
    typedef sequence <CameraAvailable_msg> CameraAvailable_msgSeq;
    module CCM_DDS::Typed <CameraAvailable_msg, CameraAvailable_msgSeq> CameraAvailable_conn; 
};

#endif // CX_SURVEILLANCEPROCESSOR_ASM__CAMERACONTROLADAPTER_COMP__PORTS__AGSP_CAMERAAVAILABLE_CONN_IDL

/// @}

