/// @defgroup AGSP_SystemStatus_conn SystemStatus_conn
/// @{
/// 
/// @file AGSP_SystemStatus_conn.idl
/// @brief SystemStatus_conn connector definition IDL file

//=========================================================

#ifndef CX_PORTS__2SURVEILLANCEPROCESSOR__AGSP_SYSTEMSTATUS_CONN_IDL
#define CX_PORTS__2SURVEILLANCEPROCESSOR__AGSP_SYSTEMSTATUS_CONN_IDL

#include <Components.idl>
#include <ccm_dds.idl>
#include "AGSP_SystemStatus_msg.idl"
#pragma ciao lem "AGSP_SystemStatus_connE.idl"

/// @brief AGSP 
module AGSP {

    /// @typedef SystemStatus_msgSeq
    typedef sequence <SystemStatus_msg> SystemStatus_msgSeq;
    module CCM_DDS::Typed <SystemStatus_msg, SystemStatus_msgSeq> SystemStatus_conn; 
};

#endif // CX_PORTS__2SURVEILLANCEPROCESSOR__AGSP_SYSTEMSTATUS_CONN_IDL

/// @}

