package CF.FilePackage;

/**
* CF/FilePackage/IOExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/

public final class IOExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public CF.FilePackage.IOException value = null;

  public IOExceptionHolder ()
  {
  }

  public IOExceptionHolder (CF.FilePackage.IOException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CF.FilePackage.IOExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CF.FilePackage.IOExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CF.FilePackage.IOExceptionHelper.type ();
  }

}
