/// @defgroup AGSP_PCPC_Cmd_obj PCPC_Cmd_obj
/// @{
/// 
/// @file AGSP_PCPC_Cmd_obj.idl
/// @brief PCPC_Cmd_obj interface definition IDL file

//=========================================================

#ifndef CX_SURVEILLANCEPROCESSOR_ASM__CAMERAMODES_ASM__POINTCLICKMODE_ASM__PC_PICTURECONTROL_COMP__PORTS__AGSP_PCPC_CMD_OBJ_IDL
#define CX_SURVEILLANCEPROCESSOR_ASM__CAMERAMODES_ASM__POINTCLICKMODE_ASM__PC_PICTURECONTROL_COMP__PORTS__AGSP_PCPC_CMD_OBJ_IDL

#pragma ciao lem "AGSP_PCPC_Cmd_objE.idl"

/// @namespace AGSP 
module AGSP {

    ///@interface PCPC_Cmd_obj 
    interface PCPC_Cmd_obj {

        void getStatus();
    };

};

#endif // CX_SURVEILLANCEPROCESSOR_ASM__CAMERAMODES_ASM__POINTCLICKMODE_ASM__PC_PICTURECONTROL_COMP__PORTS__AGSP_PCPC_CMD_OBJ_IDL

/// @}

