/// @defgroup AGSP_ScheduleStatus_msg ScheduleStatus_msg
/// @{
/// 
/// @file AGSP_ScheduleStatus_msg.idl
/// @brief ScheduleStatus_msg message definition IDL file

//=========================================================

#ifndef CX_PORTS__SCHEDULER__AGSP_SCHEDULESTATUS_MSG_IDL
#define CX_PORTS__SCHEDULER__AGSP_SCHEDULESTATUS_MSG_IDL

#include "AGSP_Common_defn.idl"
#include "AGSP_ScheduleStatus_defn.idl"
#pragma ndds typesupport "AGSP_ScheduleStatus_msgSupport.h"

/// @namespace AGSP 
module AGSP {

    /// @struct ScheduleStatus_msg
    struct ScheduleStatus_msg {
        AGSP::SystemMode modeID;
        AGSP::JobID_t jobID; //@key
        AGSP::SchedStatusEnum status;
        AGSP::SchedErrorEnum errorVal;
        AGSP::SystemTime startTime;
        unsigned long long duration;
        unsigned long long setback;
        unsigned long currentPicCount;
        unsigned long globalPicNum;
    }; //@top-level true
};

#endif // CX_PORTS__SCHEDULER__AGSP_SCHEDULESTATUS_MSG_IDL

/// @}

