/// @defgroup AGSP_HSManager_defn HSManager_defn
/// @{
/// 
/// @file AGSP_HSManager_defn.idl
/// @brief HSManager_defn definitions definition IDL file

//=========================================================

#ifndef CX_SURVEILLANCEPROCESSOR_ASM__HSMANAGER_COMP__PORTS__AGSP_HSMANAGER_DEFN_IDL
#define CX_SURVEILLANCEPROCESSOR_ASM__HSMANAGER_COMP__PORTS__AGSP_HSMANAGER_DEFN_IDL


/// @namespace AGSP 
module AGSP {

    /// @enum SPStatus
    ///
    enum SPStatus {
        SP_STATUS_PASS,
        SP_STATUS_DEGRADED,
        SP_STATUS_FAIL
    };

    /// @enum SensorStatus
    ///
    enum SensorStatus {
        SENSOR_PASS,
        SENSOR_FAIL
    };

    /// @typedef StrSeq
    typedef sequence <string> StrSeq;

    /// @struct HSConfigAttr
    struct HSConfigAttr {
        string masterName;
        long long masterId;
        AGSP::StrSeq childNames;
        boolean report;
    }; //@top-level false
};

#endif // CX_SURVEILLANCEPROCESSOR_ASM__HSMANAGER_COMP__PORTS__AGSP_HSMANAGER_DEFN_IDL

/// @}

