package com.zeligsoft.domain.dds4ccm.api.DDS4CCM.util;

import java.util.Map;

import com.google.common.collect.Maps;

import com.zeligsoft.base.zdl.staticapi.util.AbstractBaseZDLFactory;

public class DDS4CCMFactoryImpl extends AbstractBaseZDLFactory {
	protected java.util.Map<String, Class<?>> registry = Maps.newHashMap();

	public DDS4CCMFactoryImpl() {
		registry.put(
				"DDS4CCM::DDS4CCM::DDS4CCMModel",
				com.zeligsoft.domain.dds4ccm.api.DDS4CCM.impl.DDS4CCMModelZImpl.class);
		registry.put(
				"DDS4CCM::DDS4CCM::IDLFileSpecification",
				com.zeligsoft.domain.dds4ccm.api.DDS4CCM.impl.IDLFileSpecificationZImpl.class);
		registry.put(
				"DDS4CCM::DDS4CCM::IDLFileDependency",
				com.zeligsoft.domain.dds4ccm.api.DDS4CCM.impl.IDLFileDependencyZImpl.class);
		registry.put(
				"DDS4CCM::DDS4CCM::IDLIncludeDependency",
				com.zeligsoft.domain.dds4ccm.api.DDS4CCM.impl.IDLIncludeDependencyZImpl.class);
		registry.put(
				"DDS4CCM::DDS4CCM::ConnectorStatusListenerConnection",
				com.zeligsoft.domain.dds4ccm.api.DDS4CCM.impl.ConnectorStatusListenerConnectionZImpl.class);
		registry.put(
				"CORBADomain::IDL::CORBAWString",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBAWStringImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBAAnonymousArray",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBAAnonymousArrayImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBAAnonymousSequence",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBAAnonymousSequenceImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBAArray",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBAArrayImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBABoxedValue",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBABoxedValueImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBACase",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBACaseImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBAConstant",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBAConstantImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBAConstants",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBAConstantsImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBADefault",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBADefaultImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBAEnum",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBAEnumImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBAException",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBAExceptionImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBAInterface",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBAInterfaceImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBAPrimitive",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBAPrimitiveImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBASequence",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBASequenceImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBAString",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBAStringImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBAStruct",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBAStructImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBASupports",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBASupportsImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBATypeDef",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBATypeDefImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBAUnion",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBAUnionImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBAUnionField",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBAUnionFieldImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBAValue",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBAValueImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBAValueFactory",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBAValueFactoryImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBAModule",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBAModuleImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBAAttribute",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBAAttributeImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBAOperation",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBAOperationImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBANamedElement",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBANamedElementImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBAField",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBAFieldImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBAParameter",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBAParameterImplementation.class);
		registry.put(
				"CORBADomain::IDL::Native",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.NativeImplementation.class);
		registry.put(
				"CORBADomain::IDL::CORBABound",
				com.zeligsoft.domain.omg.corba.api.IDL.impl.CORBABoundImplementation.class);
		registry.put(
				"ZMLMM::ZML_Component::ComponentInterface",
				com.zeligsoft.domain.zml.api.ZML_Component.impl.ComponentInterfaceImplementation.class);
		registry.put(
				"ZMLMM::ZML_Component::StructuralRealization",
				com.zeligsoft.domain.zml.api.ZML_Component.impl.StructuralRealizationImplementation.class);
		registry.put(
				"ZMLMM::ZML_Component::Implementation",
				com.zeligsoft.domain.zml.api.ZML_Component.impl.ImplementationImplementation.class);
		registry.put(
				"ZMLMM::ZML_Component::MessagePort",
				com.zeligsoft.domain.zml.api.ZML_Component.impl.MessagePortImplementation.class);
		registry.put(
				"ZMLMM::ZML_Component::AssemblyConnector",
				com.zeligsoft.domain.zml.api.ZML_Component.impl.AssemblyConnectorImplementation.class);
		registry.put(
				"ZMLMM::ZML_Component::WorkerFunction",
				com.zeligsoft.domain.zml.api.ZML_Component.impl.WorkerFunctionImplementation.class);
		registry.put(
				"ZMLMM::ZML_Component::PortType",
				com.zeligsoft.domain.zml.api.ZML_Component.impl.PortTypeImplementation.class);
		registry.put(
				"ZMLMM::ZML_Component::Operation",
				com.zeligsoft.domain.zml.api.ZML_Component.impl.OperationImplementation.class);
		registry.put(
				"ZMLMM::ZML_Component::ConnectorEnd",
				com.zeligsoft.domain.zml.api.ZML_Component.impl.ConnectorEndImplementation.class);
		registry.put(
				"ZMLMM::ZML_Component::ComponentImplementation",
				com.zeligsoft.domain.zml.api.ZML_Component.impl.ComponentImplementationImplementation.class);
		registry.put(
				"ZMLMM::ZML_Component::InterfaceRealization",
				com.zeligsoft.domain.zml.api.ZML_Component.impl.InterfaceRealizationImplementation.class);
		registry.put(
				"ZMLMM::ZML_Component::PortTypeable",
				com.zeligsoft.domain.zml.api.ZML_Component.impl.PortTypeableImplementation.class);
		registry.put(
				"ZMLMM::ZML_Component::WorkerFunctionImpl",
				com.zeligsoft.domain.zml.api.ZML_Component.impl.WorkerFunctionImplImplementation.class);
		registry.put(
				"ZMLMM::ZML_Component::ConjugatedPort",
				com.zeligsoft.domain.zml.api.ZML_Component.impl.ConjugatedPortImplementation.class);
		registry.put(
				"ZMLMM::ZML_Component::WorkerFunctionIdentifiable",
				com.zeligsoft.domain.zml.api.ZML_Component.impl.WorkerFunctionIdentifiableImplementation.class);
		registry.put(
				"ZMLMM::ZML_Core::Parameter",
				com.zeligsoft.domain.zml.api.ZML_Core.impl.ParameterImplementation.class);
		registry.put(
				"ZMLMM::ZML_Core::Model",
				com.zeligsoft.domain.zml.api.ZML_Core.impl.ModelImplementation.class);
		registry.put(
				"ZMLMM::ZML_Core::HideableElement",
				com.zeligsoft.domain.zml.api.ZML_Core.impl.HideableElementImplementation.class);
		registry.put(
				"ZMLMM::ZML_Deployments::Allocation",
				com.zeligsoft.domain.zml.api.ZML_Deployments.impl.AllocationImplementation.class);
		registry.put(
				"ZMLMM::ZML_Deployments::Deployment",
				com.zeligsoft.domain.zml.api.ZML_Deployments.impl.DeploymentImplementation.class);
		registry.put(
				"ZMLMM::ZML_Deployments::DeploymentPart",
				com.zeligsoft.domain.zml.api.ZML_Deployments.impl.DeploymentPartImplementation.class);
		registry.put(
				"ZMLMM::ZML_Deployments::ComponentDeploymentPart",
				com.zeligsoft.domain.zml.api.ZML_Deployments.impl.ComponentDeploymentPartImplementation.class);
		registry.put(
				"ZMLMM::ZML_Deployments::DeploymentTarget",
				com.zeligsoft.domain.zml.api.ZML_Deployments.impl.DeploymentTargetImplementation.class);
		registry.put(
				"ZMLMM::ZML_Deployments::DeployableElement",
				com.zeligsoft.domain.zml.api.ZML_Deployments.impl.DeployableElementImplementation.class);
		registry.put(
				"ZMLMM::ZML_Configurations::BuildConfiguration",
				com.zeligsoft.domain.zml.api.ZML_Configurations.impl.BuildConfigurationImplementation.class);
		registry.put(
				"ZMLMM::ZML_Configurations::ConfigurationSlot",
				com.zeligsoft.domain.zml.api.ZML_Configurations.impl.ConfigurationSlotImplementation.class);
		registry.put("DDS::Topics::Topic",
				com.zeligsoft.domain.omg.dds.api.Topics.impl.TopicZImpl.class);
		registry.put(
				"DDS::Topics::TopicField",
				com.zeligsoft.domain.omg.dds.api.Topics.impl.TopicFieldZImpl.class);
		registry.put(
				"DDS::QOS::historyQosPolicy",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.historyQosPolicyZImpl.class);
		registry.put(
				"DDS::QOS::lifespanQosPolicy",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.lifespanQosPolicyZImpl.class);
		registry.put(
				"DDS::QOS::ownershipQosPolicy",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.ownershipQosPolicyZImpl.class);
		registry.put(
				"DDS::QOS::osQosPolicy",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.osQosPolicyZImpl.class);
		registry.put(
				"DDS::QOS::wdlQosPolicy",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.wdlQosPolicyZImpl.class);
		registry.put(
				"DDS::QOS::rdlQosPolicy",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.rdlQosPolicyZImpl.class);
		registry.put(
				"DDS::QOS::udQosPolicy",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.udQosPolicyZImpl.class);
		registry.put(
				"DDS::QOS::tdQosPolicy",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.tdQosPolicyZImpl.class);
		registry.put(
				"DDS::QOS::tpQosPolicy",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.tpQosPolicyZImpl.class);
		registry.put(
				"DDS::QOS::deadlineQosPolicy",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.deadlineQosPolicyZImpl.class);
		registry.put(
				"DDS::QOS::lbQosPolicy",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.lbQosPolicyZImpl.class);
		registry.put(
				"DDS::QOS::tbfQosPolicy",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.tbfQosPolicyZImpl.class);
		registry.put(
				"DDS::QOS::gdQosPolicy",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.gdQosPolicyZImpl.class);
		registry.put(
				"DDS::QOS::efQosPolicy",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.efQosPolicyZImpl.class);
		registry.put(
				"DDS::QOS::rlQosPolicy",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.rlQosPolicyZImpl.class);
		registry.put(
				"DDS::QOS::presentationQosPolicy",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.presentationQosPolicyZImpl.class);
		registry.put(
				"DDS::QOS::partitionQosPolicy",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.partitionQosPolicyZImpl.class);
		registry.put(
				"DDS::QOS::reliabilityQosPolicy",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.reliabilityQosPolicyZImpl.class);
		registry.put(
				"DDS::QOS::dsQosPolicy",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.dsQosPolicyZImpl.class);
		registry.put(
				"DDS::QOS::livelinessQosPolicy",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.livelinessQosPolicyZImpl.class);
		registry.put(
				"DDS::QOS::durabilityQosPolicy",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.durabilityQosPolicyZImpl.class);
		registry.put(
				"DDS::QOS::doQosPolicy",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.doQosPolicyZImpl.class);
		registry.put(
				"DDS::QOS::qosProperty",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.qosPropertyZImpl.class);
		registry.put("DDS::QOS::Duration",
				com.zeligsoft.domain.omg.dds.api.QOS.impl.DurationZImpl.class);
		registry.put(
				"DDS4CCM::DDSExtensions::DDSMessage",
				com.zeligsoft.domain.dds4ccm.api.DDSExtensions.impl.DDSMessageZImpl.class);
		registry.put(
				"DDS4CCM::DDSExtensions::MessageField",
				com.zeligsoft.domain.dds4ccm.api.DDSExtensions.impl.MessageFieldZImpl.class);
		registry.put(
				"DDS4CCM::QoSProfiles::QoSProfile",
				com.zeligsoft.domain.dds4ccm.api.QoSProfiles.impl.QoSProfileZImpl.class);
		registry.put(
				"DDS4CCM::QoSProfiles::QoSEntity",
				com.zeligsoft.domain.dds4ccm.api.QoSProfiles.impl.QoSEntityZImpl.class);
		registry.put(
				"DDS4CCM::QoSProfiles::DataReaderQoS",
				com.zeligsoft.domain.dds4ccm.api.QoSProfiles.impl.DataReaderQoSZImpl.class);
		registry.put(
				"DDS4CCM::QoSProfiles::ParticipantQoS",
				com.zeligsoft.domain.dds4ccm.api.QoSProfiles.impl.ParticipantQoSZImpl.class);
		registry.put(
				"DDS4CCM::QoSProfiles::PublisherQoS",
				com.zeligsoft.domain.dds4ccm.api.QoSProfiles.impl.PublisherQoSZImpl.class);
		registry.put(
				"DDS4CCM::QoSProfiles::SubscriberQoS",
				com.zeligsoft.domain.dds4ccm.api.QoSProfiles.impl.SubscriberQoSZImpl.class);
		registry.put(
				"DDS4CCM::QoSProfiles::TopicQoS",
				com.zeligsoft.domain.dds4ccm.api.QoSProfiles.impl.TopicQoSZImpl.class);
		registry.put(
				"DDS4CCM::QoSProfiles::DataWriterQoS",
				com.zeligsoft.domain.dds4ccm.api.QoSProfiles.impl.DataWriterQoSZImpl.class);
		registry.put(
				"CCM::CCM_Target::Domain",
				com.zeligsoft.domain.omg.ccm.api.CCM_Target.impl.DomainImplementation.class);
		registry.put(
				"CCM::CCM_Target::Node",
				com.zeligsoft.domain.omg.ccm.api.CCM_Target.impl.NodeImplementation.class);
		registry.put(
				"CCM::CCM_Target::NodeInstance",
				com.zeligsoft.domain.omg.ccm.api.CCM_Target.impl.NodeInstanceImplementation.class);
		registry.put(
				"CCM::CCM_Target::Interconnect",
				com.zeligsoft.domain.omg.ccm.api.CCM_Target.impl.InterconnectImplementation.class);
		registry.put(
				"CCM::CCM_Target::InterconnectInstance",
				com.zeligsoft.domain.omg.ccm.api.CCM_Target.impl.InterconnectInstanceImplementation.class);
		registry.put(
				"CCM::CCM_Target::Bridge",
				com.zeligsoft.domain.omg.ccm.api.CCM_Target.impl.BridgeImplementation.class);
		registry.put(
				"CCM::CCM_Target::BridgeInstance",
				com.zeligsoft.domain.omg.ccm.api.CCM_Target.impl.BridgeInstanceImplementation.class);
		registry.put(
				"CCM::CCM_Target::Resource",
				com.zeligsoft.domain.omg.ccm.api.CCM_Target.impl.ResourceImplementation.class);
		registry.put(
				"CCM::CCM_Target::ResourceProperty",
				com.zeligsoft.domain.omg.ccm.api.CCM_Target.impl.ResourcePropertyImplementation.class);
		registry.put(
				"CCM::CCM_Target::SharedResource",
				com.zeligsoft.domain.omg.ccm.api.CCM_Target.impl.SharedResourceImplementation.class);
		registry.put(
				"CCM::CCM_Target::RequirementSatisfier",
				com.zeligsoft.domain.omg.ccm.api.CCM_Target.impl.RequirementSatisfierImplementation.class);
		registry.put(
				"CCM::CCM_Target::SatisfierProperty",
				com.zeligsoft.domain.omg.ccm.api.CCM_Target.impl.SatisfierPropertyImplementation.class);
		registry.put(
				"CCM::CCM_Target::Requirement",
				com.zeligsoft.domain.omg.ccm.api.CCM_Target.impl.RequirementImplementation.class);
		registry.put(
				"CCM::CCM_Target::TargetAssemblyConnector",
				com.zeligsoft.domain.omg.ccm.api.CCM_Target.impl.TargetAssemblyConnectorImplementation.class);
		registry.put(
				"CCM::CCM_Target::Property",
				com.zeligsoft.domain.omg.ccm.api.CCM_Target.impl.PropertyImplementation.class);
		registry.put(
				"IDL3Plus::Generics::TypeParameter",
				com.zeligsoft.domain.idl3plus.api.Generics.impl.TypeParameterZImpl.class);
		registry.put(
				"IDL3Plus::Generics::TemplateModule",
				com.zeligsoft.domain.idl3plus.api.Generics.impl.TemplateModuleZImpl.class);
		registry.put(
				"IDL3Plus::Generics::ModuleInstantiation",
				com.zeligsoft.domain.idl3plus.api.Generics.impl.ModuleInstantiationZImpl.class);
		registry.put(
				"IDL3Plus::Generics::ParameterBinding",
				com.zeligsoft.domain.idl3plus.api.Generics.impl.ParameterBindingZImpl.class);
		registry.put(
				"IDL3Plus::Generics::TemplateModuleAlias",
				com.zeligsoft.domain.idl3plus.api.Generics.impl.TemplateModuleAliasZImpl.class);
		registry.put(
				"IDL3Plus::Generics::ModuleBinding",
				com.zeligsoft.domain.idl3plus.api.Generics.impl.ModuleBindingZImpl.class);
		registry.put(
				"IDL3Plus::Generics::TemplateSignature",
				com.zeligsoft.domain.idl3plus.api.Generics.impl.TemplateSignatureZImpl.class);
		registry.put(
				"IDL3Plus::Generics::TemplateParameterType",
				com.zeligsoft.domain.idl3plus.api.Generics.impl.TemplateParameterTypeZImpl.class);
		registry.put(
				"CCM::CCM_Component::EventPort",
				com.zeligsoft.domain.omg.ccm.api.CCM_Component.impl.EventPortImplementation.class);
		registry.put(
				"CCM::CCM_Component::CCMComponent",
				com.zeligsoft.domain.omg.ccm.api.CCM_Component.impl.CCMComponentImplementation.class);
		registry.put(
				"CCM::CCM_Component::Event",
				com.zeligsoft.domain.omg.ccm.api.CCM_Component.impl.EventImplementation.class);
		registry.put(
				"CCM::CCM_Component::Home",
				com.zeligsoft.domain.omg.ccm.api.CCM_Component.impl.HomeImplementation.class);
		registry.put(
				"CCM::CCM_Component::Manages",
				com.zeligsoft.domain.omg.ccm.api.CCM_Component.impl.ManagesImplementation.class);
		registry.put(
				"CCM::CCM_Component::StateMember",
				com.zeligsoft.domain.omg.ccm.api.CCM_Component.impl.StateMemberImplementation.class);
		registry.put(
				"CCM::CCM_Component::InterfacePort",
				com.zeligsoft.domain.omg.ccm.api.CCM_Component.impl.InterfacePortImplementation.class);
		registry.put(
				"CCM::CCM_Component::FinderOperation",
				com.zeligsoft.domain.omg.ccm.api.CCM_Component.impl.FinderOperationImplementation.class);
		registry.put(
				"CCM::CCM_Component::FactoryOperation",
				com.zeligsoft.domain.omg.ccm.api.CCM_Component.impl.FactoryOperationImplementation.class);
		registry.put(
				"CCM::CCM_Component::HomeOperation",
				com.zeligsoft.domain.omg.ccm.api.CCM_Component.impl.HomeOperationImplementation.class);
		registry.put(
				"IDL3Plus::Connectors::ConnectorDef",
				com.zeligsoft.domain.idl3plus.api.Connectors.impl.ConnectorDefZImpl.class);
		registry.put(
				"IDL3Plus::Connectors::ConnectorFragment",
				com.zeligsoft.domain.idl3plus.api.Connectors.impl.ConnectorFragmentZImpl.class);
		registry.put(
				"IDL3Plus::Connectors::FragmentImplementation",
				com.zeligsoft.domain.idl3plus.api.Connectors.impl.FragmentImplementationZImpl.class);
		registry.put(
				"IDL3Plus::Connectors::FragmentAssembly",
				com.zeligsoft.domain.idl3plus.api.Connectors.impl.FragmentAssemblyZImpl.class);
		registry.put(
				"IDL3Plus::Connectors::ConnectorImplementation",
				com.zeligsoft.domain.idl3plus.api.Connectors.impl.ConnectorImplementationZImpl.class);
		registry.put(
				"IDL3Plus::Connectors::ConnectorAssembly",
				com.zeligsoft.domain.idl3plus.api.Connectors.impl.ConnectorAssemblyZImpl.class);
		registry.put(
				"IDL3Plus::Connectors::FragmentPart",
				com.zeligsoft.domain.idl3plus.api.Connectors.impl.FragmentPartZImpl.class);
		registry.put(
				"IDL3Plus::Connectors::TypedConnector",
				com.zeligsoft.domain.idl3plus.api.Connectors.impl.TypedConnectorZImpl.class);
		registry.put(
				"IDL3Plus::Connectors::DataSpace",
				com.zeligsoft.domain.idl3plus.api.Connectors.impl.DataSpaceZImpl.class);
		registry.put(
				"IDL3Plus::Connectors::ConnectorDefaultValueBinding",
				com.zeligsoft.domain.idl3plus.api.Connectors.impl.ConnectorDefaultValueBindingZImpl.class);
		registry.put(
				"CCM::CCM_Core::CCMModel",
				com.zeligsoft.domain.omg.ccm.api.CCM_Core.impl.CCMModelImplementation.class);
		registry.put(
				"IDL3Plus::Deployment::PerPortConnectorTypeDeploymentPart",
				com.zeligsoft.domain.idl3plus.api.Deployment.impl.PerPortConnectorTypeDeploymentPartZImpl.class);
		registry.put(
				"CCM::CCM_Implementation::AssemblyImplementation",
				com.zeligsoft.domain.omg.ccm.api.CCM_Implementation.impl.AssemblyImplementationImplementation.class);
		registry.put(
				"CCM::CCM_Implementation::HomeImplementation",
				com.zeligsoft.domain.omg.ccm.api.CCM_Implementation.impl.HomeImplementationImplementation.class);
		registry.put(
				"CCM::CCM_Implementation::ManagesImpl",
				com.zeligsoft.domain.omg.ccm.api.CCM_Implementation.impl.ManagesImplImplementation.class);
		registry.put(
				"CCM::CCM_Implementation::MonolithicImplementation",
				com.zeligsoft.domain.omg.ccm.api.CCM_Implementation.impl.MonolithicImplementationImplementation.class);
		registry.put(
				"CCM::CCM_Implementation::CCMPart",
				com.zeligsoft.domain.omg.ccm.api.CCM_Implementation.impl.CCMPartImplementation.class);
		registry.put(
				"CCM::CCM_Implementation::CCMConnector",
				com.zeligsoft.domain.omg.ccm.api.CCM_Implementation.impl.CCMConnectorImplementation.class);
		registry.put(
				"CCM::CCM_Implementation::HomeInstance",
				com.zeligsoft.domain.omg.ccm.api.CCM_Implementation.impl.HomeInstanceImplementation.class);
		registry.put(
				"CCM::CCM_Deployment::DeploymentPlan",
				com.zeligsoft.domain.omg.ccm.api.CCM_Deployment.impl.DeploymentPlanImplementation.class);
		registry.put(
				"CCM::CCM_Deployment::ContainerProcess",
				com.zeligsoft.domain.omg.ccm.api.CCM_Deployment.impl.ContainerProcessImplementation.class);
		registry.put(
				"IDL3Plus::IDL3Plus::IDL3PlusModel",
				com.zeligsoft.domain.idl3plus.api.IDL3Plus.impl.IDL3PlusModelZImpl.class);
		registry.put(
				"IDL3Plus::IDL3Plus::ExtendedPortType",
				com.zeligsoft.domain.idl3plus.api.IDL3Plus.impl.ExtendedPortTypeZImpl.class);
	}

	@Override
	protected Map<String, Class<?>> getRegistry() {
		return registry;
	}
}
