package LogService.LogPackage;

/**
* LogService/LogPackage/AvailabilityStatusTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LogService.idl
* Monday, May 4, 2009 2:19:36 PM EDT
*/

public final class AvailabilityStatusTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public LogService.LogPackage.AvailabilityStatusType value = null;

  public AvailabilityStatusTypeHolder ()
  {
  }

  public AvailabilityStatusTypeHolder (LogService.LogPackage.AvailabilityStatusType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LogService.LogPackage.AvailabilityStatusTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LogService.LogPackage.AvailabilityStatusTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LogService.LogPackage.AvailabilityStatusTypeHelper.type ();
  }

}
