package LogService.LogPackage;


/**
* LogService/LogPackage/LogFullActionType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LogService.idl
* Monday, May 4, 2009 2:19:36 PM EDT
*/


/* This type specifies the action that the Log should take when its
				   internal buffers
				   become full of data, leaving no room for new records to be written.
				   Wrap indicates that the Log
				   will overwrite the oldest LogRecords with the newest records, as
				   they are written to the Log.
				   Halt indicates that the Log will stop logging when full. */
public class LogFullActionType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static LogService.LogPackage.LogFullActionType[] __array = new LogService.LogPackage.LogFullActionType [__size];

  public static final int _WRAP = 0;
  public static final LogService.LogPackage.LogFullActionType WRAP = new LogService.LogPackage.LogFullActionType(_WRAP);
  public static final int _HALT = 1;
  public static final LogService.LogPackage.LogFullActionType HALT = new LogService.LogPackage.LogFullActionType(_HALT);

  public int value ()
  {
    return __value;
  }

  public static LogService.LogPackage.LogFullActionType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected LogFullActionType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class LogFullActionType
