package LogService.LogPackage;


/**
* LogService/LogPackage/LogRecordTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LogService.idl
* Monday, May 4, 2009 2:19:36 PM EDT
*/

abstract public class LogRecordTypeHelper
{
  private static String  _id = "IDL:LogService/Log/LogRecordType:1.0";

  public static void insert (org.omg.CORBA.Any a, LogService.LogPackage.LogRecordType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static LogService.LogPackage.LogRecordType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulonglong);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (LogService.LogPackage.RecordIdTypeHelper.id (), "RecordIdType", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = LogService.LogPackage.LogTimeTypeHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "time",
            _tcOf_members0,
            null);
          _tcOf_members0 = LogService.ProducerLogRecordTypeHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "info",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (LogService.LogPackage.LogRecordTypeHelper.id (), "LogRecordType", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static LogService.LogPackage.LogRecordType read (org.omg.CORBA.portable.InputStream istream)
  {
    LogService.LogPackage.LogRecordType value = new LogService.LogPackage.LogRecordType ();
    value.id = istream.read_ulonglong ();
    value.time = LogService.LogPackage.LogTimeTypeHelper.read (istream);
    value.info = LogService.ProducerLogRecordTypeHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, LogService.LogPackage.LogRecordType value)
  {
    ostream.write_ulonglong (value.id);
    LogService.LogPackage.LogTimeTypeHelper.write (ostream, value.time);
    LogService.ProducerLogRecordTypeHelper.write (ostream, value.info);
  }

}
