package LogService.LogPackage;


/**
* LogService/LogPackage/LogRecordType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LogService.idl
* Monday, May 4, 2009 2:19:36 PM EDT
*/

public final class LogRecordType implements org.omg.CORBA.portable.IDLEntity
{
  public long id = (long)0;
  public LogService.LogPackage.LogTimeType time = null;
  public LogService.ProducerLogRecordType info = null;

  public LogRecordType ()
  {
  } // ctor

  public LogRecordType (long _id, LogService.LogPackage.LogTimeType _time, LogService.ProducerLogRecordType _info)
  {
    id = _id;
    time = _time;
    info = _info;
  } // ctor

} // class LogRecordType
