/// @defgroup AGSP_LightSensorAdapter_comp LightSensorAdapter_comp
/// @{
/// 
/// @file AGSP_LightSensorAdapter_comp.idl
/// @brief LightSensorAdapter_comp component definition IDL file

//=========================================================

#ifndef CX_SURVEILLANCEPROCESSOR_ASM__LIGHTSENSORADAPTER_COMP__SRC__AGSP_LIGHTSENSORADAPTER_COMP_IDL
#define CX_SURVEILLANCEPROCESSOR_ASM__LIGHTSENSORADAPTER_COMP__SRC__AGSP_LIGHTSENSORADAPTER_COMP_IDL

#include <Components.idl>
#pragma ciao lem "AGSP_LightSensorAdapter_compE.idl"
#include "AGSP_AuxControl_obj.idl"
#include "AGSP_StateControl_obj.idl"
#include "AGSP_LS_Status_conn.idl"

/// @namespace AGSP 
module AGSP {
    component LightSensorAdapter_comp {
        provides AGSP::AuxControl_obj AuxControlFacet;
        provides AGSP::StateControl_obj StateControlFacet;
        port LS_Status_conn::DDS_Write LS_StatusPub;
        attribute long DefaultSensitivity;
    };

};

#endif // CX_SURVEILLANCEPROCESSOR_ASM__LIGHTSENSORADAPTER_COMP__SRC__AGSP_LIGHTSENSORADAPTER_COMP_IDL

/// @}

