//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
// Copyright (c) Northrop Grumman Corporation 2010 -- ALL RIGHTS RESERVED
//==============================================================================
/// @addtogroup BasicPublisher_comp
/// @{
/// @file   SNA_Examples_defn.idl
/// @brief  Definition of enumerations used in example DDS message.
//==============================================================================

#ifndef SNA_EXAMPLES_DEFN
#define SNA_EXAMPLES_DEFN

module SNA_Examples
{
   /**
    * @enum State
    *
    * Example enumeration of states.
    */
   enum State
   {
      STATE_PASS,
      STATE_FAIL
   };

   /**
    * @enum Color
    *
    * Example enumeration of colors.
    */
   enum Color
   {
      COLOR_RED,
      COLOR_GREEN,
      COLOR_BLUE
   };

   /**
    * @typedef BoundedString
    *
    * Bounded string of size 511 ASCII characters plus a NULL terminator.
    * Bounded strings must have typedef before use in a struct. The default
    * length of a string is 255 characters plus a terminator.
    */
   typedef string<512> BoundedString;
};

#endif // SNA_EXAMPLES_DEFN

/// @}
//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
