//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
// Copyright (c) Northrop Grumman Corporation 2010 -- ALL RIGHTS RESERVED
//==============================================================================
/// @addtogroup BasicPublisher_comp
/// @{
/// @file   SNA_Examples_TestData_msg.idl
/// @brief  Definition of DDS message used in the BasicPubSub example.
//==============================================================================

#ifndef SNA_EXAMPLES_TESTDATA_MSG_IDL
#define SNA_EXAMPLES_TESTDATA_MSG_IDL

// You can include other IDL files just as in C/C++
// This file contains types used in the struct below.
#include "SNA_Examples_defn.idl"

#pragma ndds typesupport "SNA_Examples_TestData_msgSupport.h"

module SNA_Examples
{
   /**
    * @struct TestData_msg
    *
    * Example DDS message structure for the BasicPubSub example.
    */
   struct TestData_msg
   {
      /**
       * 32-bit integer.
       */
      unsigned long      myInt32;

      /**
       * 64-bit integer.
       */
      unsigned long long myInt64;

      /**
       * Double-precision floating point number.
       */
      double             myDouble;

      /**
       * Bounded ASCII string
       */
      BoundedString      myString;

      /**
       * Example enumeration
       */
      State              myState;

      /**
       * Example enumeration
       */
      Color              myColor;
   }; //@top-level true
};

#endif // SNA_EXAMPLES_TESTDATA_MSG_IDL

/// @}
//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
