module Reimport
{
	
	struct TestStruct {
		long x;
		float y;
	};
	
	enum TestEnum {
		FIELD1,
		FIELD2
	};
	
	exception TestException {
		long code;
	};
	
	exception TestException2 {
		float code;
	};
	
	const long BOB = 75;
	
	interface TestInterface {
		
		readonly attribute short testReadonly;
	
		attribute float x setraises( TestException2 ) getraises ( TestException2 );
		
		long y(in long param1, out float param2) raises( TestException );
		
	};
	
	union TestUnion switch(long)
	{
		case 1: string mem1;
  		case 2: long mem2;
		default: octet mem3;
	};
	
	typedef sequence<long> LongSequence;
	
	typedef long FooType;
	
};