//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
// Copyright (c) Northrop Grumman Corporation 2020 -- ALL RIGHTS RESERVED
//==============================================================================
//
//==============================================================================
// EXPORT REGULATIONS (EAR99)
//==============================================================================
// DISCLOSURE: 
//
// Warning - This data is subject to the Export Administration Act (Title 22 
// U.S.C. App. 2401 et seq.), as amended. The implementing regulation for 
// this statute is the Export Administration Regulations (EAR) (15 C.F.R.
// 730-774). It may not be transferred, either in its original form, derivative 
// documents, or after being incorporated into other data without first 
// obtaining approval from the U.S. government or as otherwise authorized by 
// U.S. law and regulations. 
//==============================================================================
/// @defgroup SNA_Examples_PSDDPublisher_comp PSDDPublisher_comp
/// @{
/// 
/// @file SNA_Examples_PSDDPublisher_comp.idl
/// @brief PSDDPublisher_comp component definition IDL file

//=========================================================

#ifndef CX_COMPONENTS__PSDDPUBLISHER_COMP__SRC__SNA_EXAMPLES_PSDDPUBLISHER_COMP_IDL
#define CX_COMPONENTS__PSDDPUBLISHER_COMP__SRC__SNA_EXAMPLES_PSDDPUBLISHER_COMP_IDL

#pragma componentInterface "PSDDPublisher_comp" 
#include <Components.idl>
#pragma ciao lem "SNA_Examples_PSDDPublisher_compE.idl"
#pragma conntype SNA_Examples::PSDDPublisher_comp::testDataPub PSDD_Publish
#include "SNA_Examples_PSDD_TestData_conn.idl"

/// @brief SNA_Examples 
module SNA_Examples {

    /// The PSDDPublisher_comp component is the publisher in this example. It
    /// performs the following activities:
    ///   - creates a message (sample) according to a predefined structure
    /// (SNA_Examples::TestData_msg)
    ///   - Each time it wakes up to publish, it gives a configurable number of
    /// samples to the data writer who in turn publishes them to a DDS topic.
    ///   - Uses a timer associated with it to wake up every five seconds, at
    /// which point, the publication process is repeated.
    component PSDDPublisher_comp {

        /// A DDS4CCM write port which publishes samples/messages of type
        /// SNA_Examples::TestData_msg into a DDS topic. The name and QoS of
        /// that topic are defined in the deployment plan.
        port SNA_Examples_PSDD::TestData_conn::PSDD_Publish testDataPub;

        /// Added to access config file name.
        attribute string PSDDPublisher_config;
    };

};

#endif // CX_COMPONENTS__PSDDPUBLISHER_COMP__SRC__SNA_EXAMPLES_PSDDPUBLISHER_COMP_IDL

/// @}
//==============================================================================
//                            U N C L A S S I F I E D                            
//==============================================================================
