#ifndef CX_STATEMANAGER_COMP__PORTS__SNA_EXAMPLES_STATECONTROL_OBJ_IDL
#define CX_STATEMANAGER_COMP__PORTS__SNA_EXAMPLES_STATECONTROL_OBJ_IDL

#include "SNA_Examples_Common_defn.idl"
#pragma ciao lem "SNA_Examples_StateControl_objE.idl"
#pragma ciao ami4ccm interface "SNA_Examples::StateControl_obj"
#pragma ciao lem "SNA_Examples_StateControl_objAE.idl"
#pragma ciao ami4ccm idl "SNA_Examples_StateControl_objA.idl"

module SNA_Examples {
    interface StateControl_obj {
        ReturnStatus changeState(
            in SNA_Examples::SystemState newState
            );
        SystemState getState();
    };

};

#endif
