package CF.PropertySetPackage;

/**
* CF/PropertySetPackage/InvalidConfigurationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/

public final class InvalidConfigurationHolder implements org.omg.CORBA.portable.Streamable
{
  public CF.PropertySetPackage.InvalidConfiguration value = null;

  public InvalidConfigurationHolder ()
  {
  }

  public InvalidConfigurationHolder (CF.PropertySetPackage.InvalidConfiguration initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CF.PropertySetPackage.InvalidConfigurationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CF.PropertySetPackage.InvalidConfigurationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CF.PropertySetPackage.InvalidConfigurationHelper.type ();
  }

}
