<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="umlPort" nsURI="http://www.eclipse.org/papyrus/uml/textedit/port/xtext/UmlPort"
    nsPrefix="umlPort">
  <eClassifiers xsi:type="ecore:EClass" name="PortRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="visibility" eType="#//VisibilityRule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conjugated" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeRule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeUndefined" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" eType="#//MultiplicityRule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifiers" eType="#//ModifiersRule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//DefaultValueRule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VisibilityKind">
    <eLiterals name="public" literal="+"/>
    <eLiterals name="private" value="1" literal="-"/>
    <eLiterals name="protected" value="2" literal="#"/>
    <eLiterals name="package" value="3" literal="~"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VisibilityRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//VisibilityKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="#//QualifiedName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass platform:/resource/org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualifiedName">
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="ecore:EClass platform:/resource/org.eclipse.uml2.uml/model/UML.ecore#//Namespace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="remaining" eType="#//QualifiedName"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiplicityRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bounds" upperBound="-1"
        eType="#//BoundSpecification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoundSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifiersRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//ModifierSpecification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifierSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//ModifierKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefines" eType="#//RedefinesRule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subsets" eType="#//SubsetsRule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ModifierKind">
    <eLiterals name="readOnly" literal="readOnly"/>
    <eLiterals name="union" value="1" literal="union"/>
    <eLiterals name="ordered" value="2" literal="ordered"/>
    <eLiterals name="unique" value="3" literal="unique"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RedefinesRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="ecore:EClass platform:/resource/org.eclipse.uml2.uml/model/UML.ecore#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubsetsRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="ecore:EClass platform:/resource/org.eclipse.uml2.uml/model/UML.ecore#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefaultValueRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntValue" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literalInteger" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringValue" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literalString" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BooleanLiterals">
    <eLiterals name="TRUE" literal="true"/>
    <eLiterals name="FALSE" value="1" literal="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanValue" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literalBoolean" eType="#//BooleanLiterals"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RealValue" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="integer" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fraction" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NullValue" eSuperTypes="#//Value"/>
  <eClassifiers xsi:type="ecore:EClass" name="NoValue" eSuperTypes="#//Value"/>
</ecore:EPackage>
