/*
 * generated by Xtext
 */
package org.eclipse.papyrus.uml.textedit.valuespecification.xtext.parser.antlr;

import org.eclipse.papyrus.uml.textedit.valuespecification.xtext.services.UmlValueSpecificationGrammarAccess;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import com.google.inject.Inject;

public class UmlValueSpecificationParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {

	@Inject
	private UmlValueSpecificationGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}

	@Override
	protected org.eclipse.papyrus.uml.textedit.valuespecification.xtext.parser.antlr.internal.InternalUmlValueSpecificationParser createParser(XtextTokenStream stream) {
		return new org.eclipse.papyrus.uml.textedit.valuespecification.xtext.parser.antlr.internal.InternalUmlValueSpecificationParser(stream, getGrammarAccess());
	}

	@Override
	protected String getDefaultRuleName() {
		return "AbstractRule";
	}

	public UmlValueSpecificationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UmlValueSpecificationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}

}
