/// @defgroup AGSP_SystemImages_defn SystemImages_defn
/// @{
/// 
/// @file AGSP_SystemImages_defn.idl
/// @brief SystemImages_defn definitions definition IDL file

//=========================================================

#ifndef CX_PORTS__1ARTGALLERY__AGSP_SYSTEMIMAGES_DEFN_IDL
#define CX_PORTS__1ARTGALLERY__AGSP_SYSTEMIMAGES_DEFN_IDL


/// @brief AGSP 
module AGSP {

    /// @typedef ImageArray
    typedef octet ImageArray[64000];
};

#endif // CX_PORTS__1ARTGALLERY__AGSP_SYSTEMIMAGES_DEFN_IDL

/// @}

