/// @defgroup AGSP_SystemTargets_defn SystemTargets_defn
/// @{
/// 
/// @file AGSP_SystemTargets_defn.idl
/// @brief SystemTargets_defn definitions definition IDL file

//=========================================================

#ifndef CX_PORTS__1ARTGALLERY__AGSP_SYSTEMTARGETS_DEFN_IDL
#define CX_PORTS__1ARTGALLERY__AGSP_SYSTEMTARGETS_DEFN_IDL


/// @brief AGSP 
module AGSP {

    /// @typedef SystemTargetListType
    typedef sequence <octet, 100> SystemTargetListType;
};

#endif // CX_PORTS__1ARTGALLERY__AGSP_SYSTEMTARGETS_DEFN_IDL

/// @}

