/// @defgroup AGSP_SystemTargets_conn SystemTargets_conn
/// @{
/// 
/// @file AGSP_SystemTargets_conn.idl
/// @brief SystemTargets_conn connector definition IDL file

//=========================================================

#ifndef CX_PORTS__1ARTGALLERY__AGSP_SYSTEMTARGETS_CONN_IDL
#define CX_PORTS__1ARTGALLERY__AGSP_SYSTEMTARGETS_CONN_IDL

#include <Components.idl>
#include <ccm_dds.idl>
#include "AGSP_SystemTargets_msg.idl"
#pragma ciao lem "AGSP_SystemTargets_connE.idl"

/// @namespace AGSP 
module AGSP {

    /// @typedef SystemTargets_msgSeq
    typedef sequence <SystemTargets_msg> SystemTargets_msgSeq;
    module CCM_DDS::Typed <SystemTargets_msg, SystemTargets_msgSeq> SystemTargets_conn; 
};

#endif // CX_PORTS__1ARTGALLERY__AGSP_SYSTEMTARGETS_CONN_IDL

/// @}

