/// @defgroup AGSP_SystemImages_conn SystemImages_conn
/// @{
/// 
/// @file AGSP_SystemImages_conn.idl
/// @brief SystemImages_conn connector definition IDL file

//=========================================================

#ifndef CX_PORTS__1ARTGALLERY__AGSP_SYSTEMIMAGES_CONN_IDL
#define CX_PORTS__1ARTGALLERY__AGSP_SYSTEMIMAGES_CONN_IDL

#include "AGSP_SystemImages_msg.idl"
#pragma ciao lem "AGSP_SystemImages_connE.idl"

/// @brief AGSP 
module AGSP {

    /// @typedef SystemImages_msgSeq
    ///
    /// Every DDS message type must define a sequence of that type as well, to
    /// support the instantiation of a DDS4CCM connector type for it.
    typedef sequence <SystemImages_msg> SystemImages_msgSeq;
    module CCM_PSAT::Typed <SystemImages_msg, SystemImages_msgSeq> SystemImages_conn; 
};

#endif // CX_PORTS__1ARTGALLERY__AGSP_SYSTEMIMAGES_CONN_IDL

/// @}

