grammar org.eclipse.papyrus.uml.textedit.collaborationuse.xtext.UmlCollaborationUse with org.eclipse.papyrus.uml.textedit.common.xtext.UmlCommon


import "http://www.eclipse.org/uml2/5.0.0/UML" as uml

generate umlCollaborationUse "http://www.eclipse.org/papyrus/uml/textedit/collaborationuse/xtext/UmlCollaborationUse"

CollaborationUseRule:
	visibility = VisibilityKind
	name=ID ':' (type=TypeRule | "<Undefined>");

TypeRule :
	(path=QualifiedName)? type=[uml::Collaboration] ;