/// @defgroup AGSP_MotionSensorAdapter_comp MotionSensorAdapter_comp
/// @{
/// 
/// @file AGSP_MotionSensorAdapter_comp.idl
/// @brief MotionSensorAdapter_comp component definition IDL file

//=========================================================

#ifndef CX_COMPONENTS__MOTIONSENSORADAPTER_COMP__SRC__AGSP_MOTIONSENSORADAPTER_COMP_IDL
#define CX_COMPONENTS__MOTIONSENSORADAPTER_COMP__SRC__AGSP_MOTIONSENSORADAPTER_COMP_IDL

#include <Components.idl>
#pragma ciao lem "AGSP_MotionSensorAdapter_compE.idl"
#include "AGSP_AuxControl_obj.idl"
#include "AGSP_StateControl_obj.idl"
#include "AGSP_MS_Status_conn.idl"

/// @brief AGSP 
module AGSP {
    component MotionSensorAdapter_comp {
        provides AGSP::AuxControl_obj AuxControlFacet;
        provides AGSP::StateControl_obj StateControlFacet;
        port MS_Status_conn::DDS_Write MS_StatusPub;
        attribute long DefaultSensitivity;
    };

};

#endif // CX_COMPONENTS__MOTIONSENSORADAPTER_COMP__SRC__AGSP_MOTIONSENSORADAPTER_COMP_IDL

/// @}

