/*
 * generated by Xtext
 */
package com.zeligsoft.domain.omg.corba.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class IDLUiModule extends com.zeligsoft.domain.omg.corba.dsl.ui.AbstractIDLUiModule {
	public IDLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
