/// @defgroup AGSP_AuxSensorController_comp AuxSensorController_comp
/// @{
/// 
/// @file AGSP_AuxSensorController_comp.idl
/// @brief AuxSensorController_comp component definition IDL file

//=========================================================

#ifndef CX_COMPONENTS__AUXSENSORCONTROLLER_COMP__SRC__AGSP_AUXSENSORCONTROLLER_COMP_IDL
#define CX_COMPONENTS__AUXSENSORCONTROLLER_COMP__SRC__AGSP_AUXSENSORCONTROLLER_COMP_IDL

#include <Components.idl>
#pragma ciao lem "AGSP_AuxSensorController_compE.idl"
#include "AGSP_AuxControl_obj.idl"
#include "AGSP_StateControl_obj.idl"
#include "AGSP_AuxSensorStatus_conn.idl"
#include "AGSP_CC_Status_conn.idl"
#include "AGSP_GG_Status_conn.idl"
#include "AGSP_GPS_conn.idl"
#include "AGSP_LS_Status_conn.idl"
#include "AGSP_MS_Status_conn.idl"

/// @namespace AGSP 
module AGSP {
    component AuxSensorController_comp {
        uses multiple AGSP::AuxControl_obj AuxControlRecept;
        provides AGSP::StateControl_obj StateControlFacet;
        port AuxSensorStatus_conn::DDS_Write AuxSensorStatusPub;
        port CC_Status_conn::DDS_Listen CC_StatusSub;
        port GG_Status_conn::DDS_Listen GG_StatusSub;
        port GPS_conn::DDS_Listen GPS_Sub;
        port LS_Status_conn::DDS_Listen LS_StatusSub;
        port MS_Status_conn::DDS_Listen MS_StatusSub;
    };

};

#endif // CX_COMPONENTS__AUXSENSORCONTROLLER_COMP__SRC__AGSP_AUXSENSORCONTROLLER_COMP_IDL

/// @}

