/// @defgroup AGSP_ModeUtilities_obj ModeUtilities_obj
/// @{
/// 
/// @file AGSP_ModeUtilities_obj.idl
/// @brief ModeUtilities_obj interface definition IDL file

//=========================================================

#ifndef CX_SURVEILLANCEPROCESSOR_ASM__MODEUTILITIES_COMP__PORTS__AGSP_MODEUTILITIES_OBJ_IDL
#define CX_SURVEILLANCEPROCESSOR_ASM__MODEUTILITIES_COMP__PORTS__AGSP_MODEUTILITIES_OBJ_IDL

#pragma ciao lem "AGSP_ModeUtilities_objE.idl"

/// @namespace AGSP 
module AGSP {

    ///@interface ModeUtilities_obj 
    interface ModeUtilities_obj {

        /// @param[in] inVal
        ///
        /// @param[out] outVal
        ///
        /// @param[in,out] inOutVal
        ///
        void calculate(
            in long inVal,
            out long outVal,
            inout long inOutVal
            );
    };

};

#endif // CX_SURVEILLANCEPROCESSOR_ASM__MODEUTILITIES_COMP__PORTS__AGSP_MODEUTILITIES_OBJ_IDL

/// @}

