package CF.ResourceFactoryPackage;

/**
* CF/ResourceFactoryPackage/InvalidResourceIdHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/

public final class InvalidResourceIdHolder implements org.omg.CORBA.portable.Streamable
{
  public CF.ResourceFactoryPackage.InvalidResourceId value = null;

  public InvalidResourceIdHolder ()
  {
  }

  public InvalidResourceIdHolder (CF.ResourceFactoryPackage.InvalidResourceId initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CF.ResourceFactoryPackage.InvalidResourceIdHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CF.ResourceFactoryPackage.InvalidResourceIdHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CF.ResourceFactoryPackage.InvalidResourceIdHelper.type ();
  }

}
