package CF.ResourceFactoryPackage;

/**
* CF/ResourceFactoryPackage/ShutdownFailureHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/

public final class ShutdownFailureHolder implements org.omg.CORBA.portable.Streamable
{
  public CF.ResourceFactoryPackage.ShutdownFailure value = null;

  public ShutdownFailureHolder ()
  {
  }

  public ShutdownFailureHolder (CF.ResourceFactoryPackage.ShutdownFailure initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CF.ResourceFactoryPackage.ShutdownFailureHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CF.ResourceFactoryPackage.ShutdownFailureHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CF.ResourceFactoryPackage.ShutdownFailureHelper.type ();
  }

}
