package CF.ResourceFactoryPackage;


/**
* CF/ResourceFactoryPackage/ShutdownFailure.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CF.idl
* Monday, May 4, 2009 2:19:35 PM EDT
*/

public final class ShutdownFailure extends org.omg.CORBA.UserException
{
  public String msg = null;

  public ShutdownFailure ()
  {
    super(ShutdownFailureHelper.id());
  } // ctor

  public ShutdownFailure (String _msg)
  {
    super(ShutdownFailureHelper.id());
    msg = _msg;
  } // ctor


  public ShutdownFailure (String $reason, String _msg)
  {
    super(ShutdownFailureHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class ShutdownFailure
