/// @defgroup SAAT_AttrTest_defn AttrTest_defn
/// @{
/// 
/// @file SAAT_AttrTest_defn.idl
/// @brief AttrTest_defn definitions definition IDL file

//=========================================================

#ifndef CX_PORTS__SAAT_ATTRTEST_DEFN_IDL
#define CX_PORTS__SAAT_ATTRTEST_DEFN_IDL


/// @namespace SAAT 
module SAAT {

    /// @struct LowerStruct
    struct LowerStruct {
        string testString;
        long testLong;
        short testShort;
    }; //@top-level false

    /// @typedef SeqOfStructs
    typedef sequence <LowerStruct> SeqOfStructs;

    /// @struct UpperStruct
    struct UpperStruct {
        long upperTestLong;
        short upperTestShort;
        SAAT::SeqOfStructs upperSequence;
    }; //@top-level false
};

#endif // CX_PORTS__SAAT_ATTRTEST_DEFN_IDL

/// @}

