//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
// Copyright (c) Northrop Grumman Corporation 2010 -- ALL RIGHTS RESERVED
//==============================================================================
/// @addtogroup SPOC_comp
/// @{
/// @file   SNA_Examples_SPOC_Data_conn.idl
/// @brief  Connector definition for SPOC_Data message.
//==============================================================================

#ifndef SNA_EXAMPLES_SPOC_DATA_CONN_IDL
#define SNA_EXAMPLES_SPOC_DATA_CONN_IDL

#include <ccm_dds.idl>
#include <ccm_psat.idl>

#include "SNA_Examples_SPOC_Data_msg.idl"

#pragma ciao lem "SNA_Examples_SPOC_Data_connE.idl"

module SNA_Examples 
{
   /**
    * @typedef SPOC_Data_msgSeq
    * 
    * This is the CORBA object that holds the data in the message going between
    * the SPOC_Starter and the SPOC
    */
   typedef sequence<SPOC_Data_msg> SPOC_Data_msgSeq;
   
   /**
    * @cond DOXYGEN_UNDERSTANDS_IDL3_PLUS
    * 
    * The connector object for the PSAT message 
    */
   module CCM_PSAT::Typed<SPOC_Data_msg, SPOC_Data_msgSeq> SPOC_Data_conn;
   
   /**
    * @endcond
    */
};

#endif //SNA_EXAMPLES_SPOC_DATA_CONN_IDL


/// @}
//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
