<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="langc"
    nsURI="http://www.zeligsoft.com/2008/LangC-02" nsPrefix="langc">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//UserElement #//BindableValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" lowerBound="1" eType="#//Name"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuiltInType" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//PrimitiveType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Name">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CVQualifier">
    <eLiterals name="const" value="1" literal="const"/>
    <eLiterals name="volatile" value="2"/>
    <eLiterals name="unqualified"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Struct" eSuperTypes="#//Structure"/>
  <eClassifiers xsi:type="ecore:EClass" name="Union" eSuperTypes="#//Structure"/>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" lowerBound="1"
        eType="#//ElementReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//NamedReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkage" eType="#//LinkageSpec"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultImpl" eType="#//FunctionImplementation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" lowerBound="1" eType="#//Name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ElementReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementReference" eSuperTypes="#//BindableValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="#//Element"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cvQualifier" eType="#//CVQualifier"
        defaultValueLiteral="unqualified"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pointerSpec" unique="false"
        upperBound="-1" eType="#//Pointer" defaultValueLiteral="invalid"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrayBounds" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ElementReference"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precendence" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
        volatile="true" transient="true" defaultValueLiteral="50" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionCall" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" lowerBound="1"
        eType="#//Function"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementAccess" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" lowerBound="1" eType="#//Name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//UserElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" lowerBound="1" eType="#//FileName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//Element" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declIncludes" lowerBound="1"
        eType="#//DependencyList" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defnIncludes" lowerBound="1"
        eType="#//DependencyList" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publicDirectives" upperBound="-1"
        eType="#//Directive" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="privateDirectives" upperBound="-1"
        eType="#//Directive" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PrimitiveType">
    <eLiterals name="int8"/>
    <eLiterals name="int16"/>
    <eLiterals name="int32"/>
    <eLiterals name="uint8"/>
    <eLiterals name="uint16"/>
    <eLiterals name="uint32"/>
    <eLiterals name="char"/>
    <eLiterals name="float"/>
    <eLiterals name="double"/>
    <eLiterals name="void"/>
    <eLiterals name="long"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" abstract="true" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primitiveType" lowerBound="1"
        eType="#//PrimitiveType" changeable="false" volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegralLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bytes" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signed" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CharacterLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatingLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnStatement" eSuperTypes="#//ExpressionStatement"/>
  <eClassifiers xsi:type="ecore:EEnum" name="LinkageSpec">
    <eLiterals name="unspecified"/>
    <eLiterals name="extern" value="1"/>
    <eLiterals name="static" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeBlock" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="forceBraces" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryOperation" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//Operator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Operator">
    <eLiterals name="add"/>
    <eLiterals name="subtract"/>
    <eLiterals name="assign"/>
    <eLiterals name="bitwise_or"/>
    <eLiterals name="bitwise_and"/>
    <eLiterals name="assign_add"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Pointer">
    <eLiterals name="pointer" value="1" literal="pointer"/>
    <eLiterals name="const_pointer" value="2" literal="const_pointer"/>
    <eLiterals name="invalid" literal=""/>
    <eLiterals name="volatile_pointer"/>
    <eLiterals name="const_volatile_pointer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Structure" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//NamedReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionPointer" eSuperTypes="#//UserElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" lowerBound="1"
        eType="#//ElementReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//ElementReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionAddress" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" lowerBound="1"
        eType="#//Function"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkage" lowerBound="1"
        eType="#//LinkageSpec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="#//ElementReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initializer" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Typedef" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="#//ElementReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MemberAccess" eSuperTypes="#//ElementAccess">
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionBlob" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ElementKind">
    <eLiterals name="default" literal=""/>
    <eLiterals name="headerOnly" value="1"/>
    <eLiterals name="implOnly" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="files" upperBound="-1"
        eType="#//ElementList"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="folders" upperBound="-1"
        eType="#//FolderName" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publicFolders" upperBound="-1"
        eType="#//FolderName" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enum" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumerators" upperBound="-1"
        eType="#//Enumerator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enumerator" eSuperTypes="#//BindableValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//IntegralLiteral"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" lowerBound="1" eType="#//Name"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileDependency" abstract="true" eSuperTypes="#//Dependency">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filename" lowerBound="1"
        eType="#//FileName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemInclude" eSuperTypes="#//FileDependency"/>
  <eClassifiers xsi:type="ecore:EClass" name="UserInclude" eSuperTypes="#//FileDependency"/>
  <eClassifiers xsi:type="ecore:EClass" name="FileName" eSuperTypes="#//Name">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasObjectCode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FolderName" eSuperTypes="#//Name">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="api" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CastExpr" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetType" lowerBound="1"
        eType="#//ElementReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserElement" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ElementKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defn" eType="#//FileName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependencyList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//Dependency" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SizeofType" eSuperTypes="#//Sizeof">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="#//ElementReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BindableValue" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemFileName" eSuperTypes="#//FileName"/>
  <eClassifiers xsi:type="ecore:EClass" name="SwitchClause" eSuperTypes="#//CodeBlock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fallthrough" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabeledClause" eSuperTypes="#//SwitchClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="labels" lowerBound="1"
        upperBound="-1" eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SwitchStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clauses" upperBound="-1"
        eType="#//SwitchClause" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BreakStatement" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddressOfExpr" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DereferenceExpr" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhileStatement" eSuperTypes="#//CodeBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Macro" eSuperTypes="#//Directive #//BindableValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Name" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="replacement" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" lowerBound="1" eType="#//Name"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Directive" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclarationStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//VariableDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlockInitializer" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exprs" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexExpr" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="array" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalComparison" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//BooleanOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BooleanOperator">
    <eLiterals name="and"/>
    <eLiterals name="or"/>
    <eLiterals name="less_than"/>
    <eLiterals name="greater_than"/>
    <eLiterals name="less_than_equal"/>
    <eLiterals name="greater_than_equal"/>
    <eLiterals name="equivalent"/>
    <eLiterals name="not_equivalent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SizeofExpr" eSuperTypes="#//Sizeof">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sizeof" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionImplementation" eSuperTypes="#//UserElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//CodeBlock"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" lowerBound="1"
        eType="#//Function"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subSystems" upperBound="-1"
        eType="#//SubSystem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publicFolders" upperBound="-1"
        eType="#//FolderName" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifacts" upperBound="-1"
        eType="#//LinkableArtifact" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeBlob" eSuperTypes="#//CodeBlock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" lowerBound="1"
        eType="#//DependencyBlob" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="markerComment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DependencyBlob" eSuperTypes="#//Dependency">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="markerComment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkableArtifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionImplementations"
        upperBound="-1" eType="#//FunctionImplementation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootElements" upperBound="-1"
        eType="#//UserElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalStatement" eSuperTypes="#//CodeBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
