/**
 * generated by Xtext
 */
package org.eclipse.papyrus.infra.gmfdiag.css3.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class CSSProposalProvider extends AbstractCSSProposalProvider {
}
