/// @defgroup AGSP_SystemImages_defn SystemImages_defn
/// @{
/// 
/// @file AGSP_SystemImages_defn.idl
/// @brief SystemImages_defn definitions definition IDL file

//=========================================================

#ifndef CX_SURVEILLANCEPROCESSOR_ASM__MISSIONCONTROLBRIDGE_COMP__PORTS__AGSP_SYSTEMIMAGES_DEFN_IDL
#define CX_SURVEILLANCEPROCESSOR_ASM__MISSIONCONTROLBRIDGE_COMP__PORTS__AGSP_SYSTEMIMAGES_DEFN_IDL


/// @namespace AGSP 
module AGSP {

    /// @typedef ImageArray
    typedef octet ImageArray[63999-0+1];
};

#endif // CX_SURVEILLANCEPROCESSOR_ASM__MISSIONCONTROLBRIDGE_COMP__PORTS__AGSP_SYSTEMIMAGES_DEFN_IDL

/// @}

