/// @defgroup AGSP_SystemImages_conn SystemImages_conn
/// @{
/// 
/// @file AGSP_SystemImages_conn.idl
/// @brief SystemImages_conn connector definition IDL file

//=========================================================

#ifndef CX_SURVEILLANCEPROCESSOR_ASM__MISSIONCONTROLBRIDGE_COMP__PORTS__AGSP_SYSTEMIMAGES_CONN_IDL
#define CX_SURVEILLANCEPROCESSOR_ASM__MISSIONCONTROLBRIDGE_COMP__PORTS__AGSP_SYSTEMIMAGES_CONN_IDL

#include <ccm_psat.idl>
#include "AGSP_SystemImages_msg.idl"
#pragma ciao lem "AGSP_SystemImages_connE.idl"

/// @namespace AGSP 
module AGSP {

    /// @typedef SystemImages_msgSeq
    typedef sequence <SystemImages_msg> SystemImages_msgSeq;
    module CCM_PSAT::Typed <SystemImages_msg, SystemImages_msgSeq> SystemImages_conn; 
};

#endif // CX_SURVEILLANCEPROCESSOR_ASM__MISSIONCONTROLBRIDGE_COMP__PORTS__AGSP_SYSTEMIMAGES_CONN_IDL

/// @}

