/// @defgroup AGSP_Targets_msg Targets_msg
/// @{
/// 
/// @file AGSP_Targets_msg.idl
/// @brief Targets_msg message definition IDL file

//=========================================================

#ifndef CX_SURVEILLANCEPROCESSOR_ASM__CAMERAMODES_ASM__PORTS__AGSP_TARGETS_MSG_IDL
#define CX_SURVEILLANCEPROCESSOR_ASM__CAMERAMODES_ASM__PORTS__AGSP_TARGETS_MSG_IDL

#include "AGSP_Targets_defn.idl"
#pragma ndds typesupport "AGSP_Targets_msgSupport.h"

/// @namespace AGSP 
module AGSP {

    /// @struct Targets_msg
    struct Targets_msg {

        /// // Sequence of target reports
        long numTargets;
        AGSP::TargetListType targetList;
    }; //@top-level true
};

#endif // CX_SURVEILLANCEPROCESSOR_ASM__CAMERAMODES_ASM__PORTS__AGSP_TARGETS_MSG_IDL

/// @}

