/// @defgroup SNA_Examples_IDLExtraExtra_defn IDLExtraExtra_defn
/// @{
/// 
/// @file SNA_Examples_IDLExtraExtra_defn.idl
/// @brief IDLExtraExtra_defn definitions definition IDL file

//=========================================================

#ifndef CX_SNA_EXAMPLES_IDLEXTRAEXTRA_DEFN_IDL
#define CX_SNA_EXAMPLES_IDLEXTRAEXTRA_DEFN_IDL

#include "SNA_Examples_IDLExtra_defn.idl"

/// @namespace SNA_Examples 
module SNA_Examples {

    /// @typedef CORBAString
    typedef string<777> CORBAString;

    /// @typedef CORBAArray
    typedef CORBAString CORBAArray[MAX][5];
};

#endif // CX_SNA_EXAMPLES_IDLEXTRAEXTRA_DEFN_IDL

/// @}

