/// @defgroup SNA_Examples_IDL_defn IDL_defn
/// @{
/// 
/// @file SNA_Examples_IDL_defn.idl
/// @brief IDL_defn definitions definition IDL file

//=========================================================

#ifndef CX_SNA_EXAMPLES_IDL_DEFN_IDL
#define CX_SNA_EXAMPLES_IDL_DEFN_IDL

#include "SNA_Examples_IDLExtra_defn.idl"
#include <ccm_dds.idl>

/// @namespace SNA_Examples 
module SNA_Examples {

    /// @typedef SequenceConstantBound
    typedef sequence <long, MAX> SequenceConstantBound;

    /// @typedef CORBAWString
    typedef wstring<MAX> CORBAWString;

    /// @idlexcept CORBAException
    exception CORBAException {

        /// @publicsection CORBAField
        CCM_DDS::AlreadyCreated CORBAField;
    };

    /// @typedef Sequence
    typedef sequence <long, 555> Sequence;
};

#endif // CX_SNA_EXAMPLES_IDL_DEFN_IDL

/// @}

