//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
// Copyright (c) Northrop Grumman Corporation 2010 -- ALL RIGHTS RESERVED
//==============================================================================
/// @addtogroup PubSubClientServer_comp
/// @{
/// @file   SNA_Examples_NumAssert_conn.idl
/// @brief  Definition of DDS message used in the PubSubClientServer example.
//==============================================================================

#ifndef SNA_EXAMPLES_NUMASSERT_CONN_IDL
#define SNA_EXAMPLES_NUMASSERT_CONN_IDL

#include <ccm_dds.idl>

// Must include message definition to use with connector
#include "SNA_Examples_NumAssert_msg.idl"

#pragma ciao lem "SNA_Examples_NumAssert_connE.idl"

module SNA_Examples
{ 
   /**
    * @typedef NumAssert_msgSeq
    *
    * Sequence of top-level message of type SNA_Examples::NumAssert to use with
    * the DDS4CCM templated module instantiation.
    */
   typedef sequence<NumAssert_msg> NumAssert_msgSeq;

   /**
    * @cond DOXYGEN_UNDERSTANDS_IDL3_PLUS
    * 
    * Instantiation of the DDS4CCM typed module for type NumAssert_msg
    */
   module ::CCM_DDS::Typed<NumAssert_msg, NumAssert_msgSeq> NumAssert_conn;
   
   /**
    * @endcond
    */
};

#endif // SNA_EXAMPLES_NUMASSERT_CONN_IDL

/// @}
//==============================================================================
//                         U N C L A S S I F I E D
//==============================================================================
